### ISSUE TITLE
"CameraPositionState may only be associated with one GoogleMap at a time" when used with Accompanist's HorizontalPager

### ISSUE THREAD

**Issue by nathanjde** [googlemaps/android-maps-compose#106]
Coming across a crash when trying to embed a `GoogleMap` inside a `HorizontalPager` when the `CameraPositionState` is hoisted outside of the pager

#### Environment details
* Android Studio `Bumblebee 2021.1.1 Patch 3`
* Kotlin `1.6.20`
* Compose `1.2.0-alpha08`
* Accompanist `0.24.7-alpha`
* maps-compose `2.1.0`

#### Steps to reproduce

* I've created a demo of the bug here: https://github.com/nathanjde/pagerbug-maps-compose (based off the android-maps-compose demo repo and a [single additional commit](https://github.com/nathanjde/pagerbug-maps-compose/commit/65e1881f80333333a673b762775bfe5023af5dfc)
* Bug can be reproduced when swiping to the last pager page and back again to the first, or by clicking on any "Details" pager tab and back to the map again

#### Stack trace
```
java.lang.IllegalStateException: CameraPositionState may only be associated with one GoogleMap at a time
    at com.google.maps.android.compose.CameraPositionState.setMap$maps_compose_release(CameraPositionState.kt:144)
    at com.google.maps.android.compose.MapPropertiesNode.<init>(MapUpdater.kt:40)
    at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$1.invoke(MapUpdater.kt:121)
    at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$1.invoke(MapUpdater.kt:119)
    at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$$inlined$ComposeNode$1.invoke(Composables.kt:225)
...
```

**Comment by jpoehnelt** [comment]
@nathanjde Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by arriolac** [comment]
There is code that is supposed to disassociate the map with the `CameraPositionState` object see: https://github.com/googlemaps/android-maps-compose/blob/main/maps-compose/src/main/java/com/google/maps/android/compose/MapUpdater.kt#L95 so I wonder if the `GoogleMap` composable isn't properly disposing within a horizontal pager/
