### ISSUE TITLE
Marker info window jumps to another marker if the original marker leaves composition

### ISSUE THREAD

**Issue by molnarjozsef** [googlemaps/android-maps-compose#225]
[markerInfoWindow.webm](https://user-images.githubusercontent.com/46760009/202757265-accdc8a1-3758-477e-a5d8-e19f5d507d7a.webm)

[markerInfoWindow2.webm](https://user-images.githubusercontent.com/46760009/202760592-4dc96fc5-c4d0-443d-96a3-6513fc885529.webm)

On the second video you can see that it's not the marker itself that changes position, it's only the info window.
To reproduce this, I only added these sections to the BasicMapActivity of the sample app of this repository.
```    
val states = listOf(singaporeState, singapore2State, singapore3State)
val visibleStates = remember { mutableStateOf(states) }

LaunchedEffect(cameraPositionState.position) {
    visibleStates.value = states.filter {
        cameraPositionState.projection?.visibleRegion?.latLngBounds?.contains(it.position) == true
    }
}
```
```
visibleStates.value.forEach {
    Marker(
        state = it,
        title = "Marker in Singapore",
        onClick = markerClick,
        // rotation = state.position.latitude.toFloat() * 2400f
    )
}
```

Sometimes it even crashes with the following stacktrace:
```
2022-11-18 17:36:10.561 5475-5475/com.google.maps.android.compose E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.maps.android.compose, PID: 5475
    java.lang.IllegalStateException: MarkerState may only be associated with one Marker at a time.
        at com.google.maps.android.compose.MarkerState.setMarker$maps_compose_debug(Marker.kt:88)
        at com.google.maps.android.compose.MarkerNode.onAttached(Marker.kt:46)
        at com.google.maps.android.compose.MapApplier.insertBottomUp(MapApplier.kt:53)
        at com.google.maps.android.compose.MapApplier.insertBottomUp(MapApplier.kt:34)
        at androidx.compose.runtime.ComposerImpl$createNode$3.invoke(Composer.kt:1548)
        at androidx.compose.runtime.ComposerImpl$createNode$3.invoke(Composer.kt:1543)
        at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3395)
        at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3392)
        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:782)
        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:813)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:526)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)

```

I tested it on API 31 and 33, on v2.7.2.

**Comment by DSteve595** [comment]
This is due to the lack of keying of composables emitted in the `forEach`.
```kotlin
visibleStates.value.forEach { marker ->
  Marker(state = marker, /* ... */)
}
```
Here, each `Marker` composable's "identity" is simply its position in the list. This is fine for the first composition, but that position isn't stable, so once an item is removed from the list, another composable's state gets clobbered. You can see similar problems outside of Maps, where items' states replace each other upon structurally changing a list.
A good fix is to use the `key` composable to clarify the identity of each Marker:
```kotlin
visibleStates.value.forEach { marker ->
  key(marker) { // each `marker` instance is unique, making it a good key
    Marker(state = marker, /* ... */)
  }
}
```
This fixes the issue:
[markers-with-keys.webm](https://user-images.githubusercontent.com/1078569/203180942-a72657db-2c8c-4ebb-8288-8aa594a2b05d.webm)

Closing this as won't-fix, but open to suggestions for API/doc improvements.

**Comment by molnarjozsef** [comment]
Thanks, it did indeed fix my issue! :)
