### ISSUE TITLE
StreetView Composable crashes with some locations

### ISSUE THREAD

**Issue by moallemi** [googlemaps/android-maps-compose#265]
#### Environment details

1. StreetView Composable
2. Google Pixel 6 Pro - Android 13
3. android:maps-compose:2.9.1 / com.google.maps.android:maps:3.4.0 / play-services-maps:18.1.0

#### Steps to reproduce

  1. Open StreetViewActivity in sample of this repo with this `latitude=32.429634, longitude=-96.828891`

#### Code example
The **fast path** to reproduce: Change current singapore 
```
val singapore = LatLng(1.35, 103.87)
```
to 
```
val singapore = LatLng(32.429634, -96.828891)
```

and run the sample app and navigate to Street View from Main Activity

#### Stack trace
```
com.google.maps.api.android.lib6.common.apiexception.f: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.dynamite_mapsdynamite@214218113@21.42.18 (190400-0):23)
	at com.google.maps.api.android.lib6.streetview.camera.e.run(:com.google.android.gms.dynamite_mapsdynamite@214218113@21.42.18 (190400-0):0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
	at com.google.maps.android.compose.streetview.StreetViewPanoramaPropertiesNode.onAttached$lambda$3(Unknown Source:7)
	at com.google.maps.android.compose.streetview.StreetViewPanoramaPropertiesNode.$r8$lambda$u0P0-MFqw789nPtol3qohzgcP-I(Unknown Source:0)
	at com.google.maps.android.compose.streetview.StreetViewPanoramaPropertiesNode$$ExternalSyntheticLambda3.onStreetViewPanoramaChange(Unknown Source:2)
	at com.google.android.gms.maps.zzai.zzb(com.google.android.gms:play-services-maps@@18.0.0:1)
	at com.google.android.gms.maps.internal.zzbk.zza(com.google.android.gms:play-services-maps@@18.0.0:2)
	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.0.0:3)
	at android.os.Binder.transact(Binder.java:1064)
	at dw.aZ(:com.google.android.gms.dynamite_mapsdynamite@214218113@21.42.18 (190400-0):2)
	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.dynamite_mapsdynamite@214218113@21.42.18 (190400-0):22)
	at com.google.maps.api.android.lib6.streetview.camera.e.run(:com.google.android.gms.dynamite_mapsdynamite@214218113@21.42.18 (190400-0):0) 
	at android.os.Handler.handleCallback(Handler.java:938) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7839) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@moallemi Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by moallemi** [comment]
I tried to open this location with google maps intent:

`adb shell am start -a "android.intent.action.VIEW" -d "google.streetview:cbll=32.429634,-96.828891"`

And it seems that this location is not supported by street view. So is there any way to catch the exception?

<img width="550" alt="CleanShot 2023-02-15 at 13 52 34@2x" src="https://user-images.githubusercontent.com/1250691/219177129-e6f109d0-413f-427c-bc07-e6488d4e8a6d.png">

**Comment by yusufonderd** [comment]
Same issue. I'm getting same exception in some location points.

**Comment by moallemi** [comment]
@StephenVinouze You can check the availability with streetview REST API for now

**Comment by wangela** [comment]
Hi folks, @kikoso has drafted a PR for a new utility in android-maps-utils that does the work of checking whether a Street View panorama exists at the desired location, so you can call that first and only request a Street View panorama if one exists. Take a look at the [issue](https://github.com/googlemaps/android-maps-utils/issues/1201) and [associated PR](https://github.com/googlemaps/android-maps-utils/pull/1200) to comment on whether that would help in handling locations where Street View is not available.

**Comment by wangela** [comment]
The Street View metadata util is now available in `com.google.maps.android:android-maps-utils:3.5.0` to help make a free request to check existence of a Street View panorama at a given location before requesting the panorama. [Usage instructions.](https://github.com/googlemaps/android-maps-utils#street-view-metadata-utility)

To resolve this bug, add a step to the Street View composable implementation to use the StreetViewUtil before requesting a panorama.

**Comment by lawm** [comment]
Will there be a change in android-maps-compose to avoid the crash? Or show us how to catch the exception?

**Comment by wangela** [comment]
I agree wtih @kikoso's recommendation to leave the metadata check to the developer, so we keep the Compose library true to the scope of the Maps SDK and do not force high-volume, latency-inducing metadata checks in use cases where the developer is confident that the panoramas exist.

**Comment by wangela** [comment]
Please make sure you have `maps-compose-utils` v3.0.0 or later and enable the Street View Static API on the project associated with your API key using the instructions at https://goo.gle/enable-sv-static-api in order to use the `fetchStreetViewData` method.

**Comment by amatanat** [comment]
Hi @wangela. We wanna restrict `source` to `outdoor` only. However `fetchStreetViewData` doesn't support it currently. Would it be possible to extend API with this option? I can create a new issue/feature request 🙂 .

**Comment by yusufonderd** [comment]
> Hi @wangela. We wanna restrict `source` to `outdoor` only. However `fetchStreetViewData` doesn't support it currently. Would it be possible to extend API with this option? I can create a new issue/feature request 🙂 .

I already opened a pr for this:  https://github.com/googlemaps/android-maps-utils/pull/1262

**Comment by yogeshButani** [comment]
@kikoso 
@yusufonderd 
@amatanat 
@wangela 
@lawm 
@moallemi 
@StephenVinouze 

Hey all! i have used package flutter_google_street_view: ^3.1.4 for street view in my app, but my app getting crashes everytime by giving below error in console
Process: com.cwt.tripstr, PID: 5735
E/AndroidRuntime( 5735): com.google.maps.api.android.lib6.common.apiexception.f: java.lang.NullPointerException: Parameter specified as non-null is null: method zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange, parameter location
E/AndroidRuntime( 5735): 	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.policy_maps_core_dynamite@242112603@242112601042.642028603.642028603:318)
E/AndroidRuntime( 5735): 	at com.google.maps.api.android.lib6.streetview.camera.e.run(:com.google.android.gms.policy_maps_core_dynamite@242112603@242112601042.642028603.642028603:3)
E/AndroidRuntime( 5735): 	at android.os.Handler.handleCallback(Handler.java:959)
E/AndroidRuntime( 5735): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 5735): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime( 5735): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime( 5735): 	at android.app.ActivityThread.main(ActivityThread.java:8699)
E/AndroidRuntime( 5735): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime( 5735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
E/AndroidRuntime( 5735): Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange, parameter location
E/AndroidRuntime( 5735): 	at zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange(Unknown Source:2)



Does anyone have solution for this?
App is crashing also even streetview is available
