### ISSUE TITLE
NoSuchElementException when setting Image composable in clusterContent

### ISSUE THREAD

**Issue by vashisthg** [googlemaps/android-maps-compose#271]
#### Environment details

1. compileSdkVersion 33, targetSdkVersion 32
2. OS Version on emulator - Api 33
3.  "com.google.maps.android:maps-compose:2.11.0" and "com.google.maps.android:maps-compose-utils:2.11.0"

#### Steps to reproduce

  1. Put an image in the clusterContent lambda in the `Clustering` composable. The items are in thousands.  See code example
  2. Run the app.   
  3. You will be able to see clusters.App crashes      
  4. Now zoom in more.
  5. App crashes.
  6. Set clusterContent = null, the the app doesn't crash on zooming in. 

#### Code example

```
  clusterContent = {
                    Image(
                        modifier = Modifier.wrapContentSize(),
                        painter = painterResource(
                            R.drawable.XYZ
                        ),
                        contentDescription = null,
                    )
                }
```

#### Stack trace

```

    java.util.NoSuchElementException: Collection contains no element matching the predicate.
                                                             	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.getDescriptorForCluster(ClusterRenderer.kt:234)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer.onBeforeClusterRendered(DefaultClusterRenderer.java:913)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1073)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2400(DefaultClusterRenderer.java:1021)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:738)
                                                             	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:707)
                                                             	
```

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@vashisthg Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by DSteve595** [comment]
Would you be able to provide a repro project? I'm having trouble repro'ing.

**Comment by DSteve595** [comment]
Got a repro! Seems to be timing-related, more likely to occur when rendering lots of items. Working on a fix.
