### ISSUE TITLE
Clustering causes a crash in Navigation.

### ISSUE THREAD

**Issue by matsudamper** [googlemaps/android-maps-compose#297]
#### Environment details
maps-compose: 2.11.3

#### Steps to reproduce
1. using Clustering.
2. Switch Screen.
3. The size of View becomes 0 by timing.
4. Create a Bitmap with 0 size and it crashes.
https://github.com/googlemaps/android-maps-compose/blob/c82444f2aab16a6f6e0ad953edb03d262f213d9d/maps-compose-utils/src/main/java/com/google/maps/android/compose/clustering/ClusterRenderer.kt#L177-L181

#### Code example
Since it happens occasionally, I switch it many times.
```kotlin
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                var showMap by remember {
                    mutableStateOf(true)
                }
                val items = remember {
                    (0..100).map { ClusterItemImpl(it) }
                }
                LaunchedEffect(Unit) {
                    while (isActive) {
                        delay(100 + Random.nextLong(400))
                        showMap = !showMap
                    }
                }

                if (showMap) {
                    GoogleMap(modifier = Modifier.fillMaxSize()) {
                        Clustering(
                            items = items,
                            clusterContent = {
                                Text(text = "size=${it.size}")
                            },
                            clusterItemContent = { item ->
                                Text(text = item.title)
                            }
                        )
                    }
                }
            }
        }
    }
}

class ClusterItemImpl(private val index: Int) : ClusterItem {
    override fun getPosition(): LatLng = LatLng(0.toDouble(), 0.toDouble())
    override fun getTitle(): String = index.toString()
    override fun getSnippet(): String? = null
}
```

#### Stack trace
```
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1145)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1111)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1059)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:1018)
    at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.renderViewToBitmapDescriptor(ClusterRenderer.kt:177)
    at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.getDescriptorForCluster(ClusterRenderer.kt:150)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer.onBeforeClusterRendered(DefaultClusterRenderer.java:884)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1044)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2300(DefaultClusterRenderer.java:992)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:707)
    at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:678)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8128)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
```

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@matsudamper Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by matsudamper** [comment]
If there is no problem with the policy, you can submit the modified code.
https://github.com/matsudamper/android-maps-compose/commit/b767c73e456f01675896c6a8804feeaf6eba8231

**Comment by levinzonr** [comment]
Also encountered it by navigating back from the Screen with Clustering (Jetpack Compose Navigation)
Any updates on this?

**Comment by Nicoslz** [comment]
I have also encountered this problem. It makes the application's Navigation completely unusable if I use clustering on the Google Maps.

And updates on this issue?

**Comment by VITYQ** [comment]
Also have this problem. Any solutions?
