### ISSUE TITLE
Clustering is broken

### ISSUE THREAD

**Issue by Sepho** [googlemaps/android-maps-compose#309]
I tried to implement a very simple clustering sample app using latest version of google maps compose library. When I use `Clustering` composable function and run app crashes when is trying to render the map. 

Steps to reproduce:

 1. Create new Android project using Compose Material template

 2. Add these dependencies

    ```
    implementation 'com.google.maps.android:maps-compose:2.11.4'

    // Make sure to also include the latest version of the Maps SDK for Android
    implementation 'com.google.android.gms:play-services-maps:18.1.0'

    // Optionally, you can include the Compose utils library for Clustering, etc.
    implementation 'com.google.maps.android:maps-compose-utils:2.11.4'

    // Optionally, you can include the widgets library for ScaleBar, etc.
    implementation 'com.google.maps.android:maps-compose-widgets:2.11.4'
    ```
 
 3. Add a valid google maps key inside `<application>` tag in `AndroidManifest.xml`

    ```
    <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="YOUR_KEY"
            />
    ```
 4.  Add following code to `MainActivity` inside `setContent` block

   ```
    val singapore = LatLng(1.35, 103.87)
        
    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(singapore, 10f)
    }

    GoogleMap(
        modifier = Modifier.fillMaxSize(), 
        cameraPositionState = cameraPositionState
    ) {
        Clustering(items = listOf(MyMarker("foo")))
    }
    ```

 5. Create `MyMarker` data class (just a dummy class which implements `ClusterItem` interface)

    ```
    data class MyMarker(val name: String): ClusterItem {
        override fun getPosition(): LatLng {
            return LatLng(1.30, 103.80)
        } 

        override fun getTitle(): String? {
            return name
        }

       override fun getSnippet(): String? {
           return null
       }
    }
    ```

With those simple changes I should see a full screen map with just one unclustered marker. But instead I get this error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.mapstest, PID: 7196
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/widget/AppCompatTextView;
        at com.google.maps.android.clustering.ClusterManager.<init>(ClusterManager.java:78)
        at com.google.maps.android.clustering.ClusterManager.<init>(ClusterManager.java:70)
        at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invokeSuspend(Clustering.kt:104)
        at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invoke(Unknown Source:23)
        at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invoke(Unknown Source:6)
        at com.google.maps.android.compose.MapEffectKt$MapEffect$1.invokeSuspend(MapEffect.kt:26)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@10983c0, androidx.compose.runtime.BroadcastFrameClock@db1c8f9, StandaloneCoroutine{Cancelling}@984a03e, AndroidUiDispatcher@6e31bec]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.AppCompatTextView" on path: DexPathList[[dex file "/data/data/com.example.mapstest/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~a3y1RK-lr6Zj89PHaClKpA==/com.example.mapstest-_VL6f5R9fXVZhEg4iRdmhQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~a3y1RK-lr6Zj89PHaClKpA==/com.example.mapstest-_VL6f5R9fXVZhEg4iRdmhQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

What am I missing? I am set `minSdk 24` and both `compileSdk` and `targetSkd` 33 version.

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@Sepho Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by cbeyls** [comment]
I have the same issue and I have no idea why. The clustering library doesn't seem to depend on AppCompat, yet the classloader tries to load AppCompatTextView. If AppCompat is missing from the project dependencies, the app crashes when building the clustering.

The sample project includes AppCompat in its dependencies (throught material components) so can't be used to reproduce the issue.
