### ISSUE TITLE
GoogleMap crash on load + destroy

### ISSUE THREAD

**Issue by polivmi1** [googlemaps/android-maps-compose#313]
Please be sure to include as much information as possible:

#### Environment details

Any OS
2.11.4

#### Steps to reproduce

  1. load map in background while a dialog is shown
  2. dialog triggers map to be dismissed
  3. most likely the map didn't fully load and that's why something that doesn't exist is trying to be cleared up

#### Stack trace
```
FATAL EXCEPTION: main
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.LinkedList.isEmpty()' on a null object reference
                                                                                                    	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zae(com.google.android.gms:play-services-base@@18.2.0:1)
                                                                                                    	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onDestroy(com.google.android.gms:play-services-base@@18.2.0:2)
                                                                                                    	at com.google.android.gms.maps.MapView.onDestroy(com.google.android.gms:play-services-maps@@18.1.0:1)
                                                                                                    	at com.google.maps.android.compose.GoogleMapKt$MapLifecycle$2$invoke$$inlined$onDispose$1.dispose(Effects.kt:485)
                                                                                                    	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:85)
                                                                                                    	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1094)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:624)
                                                                                                    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.disposeCurrentNodes(SubcomposeLayout.kt:712)
                                                                                                    	at androidx.compose.ui.layout.SubcomposeLayoutState.disposeCurrentNodes$ui_release(SubcomposeLayout.kt:230)
                                                                                                    	at androidx.compose.ui.layout.SubcomposeLayoutKt$SubcomposeLayout$5$1$invoke$$inlined$onDispose$1.dispose(Effects.kt:485)
                                                                                                    	at androidx.compose.runtime.DisposableEffectImpl.onForgotten(Effects.kt:85)
                                                                                                    	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1094)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:820)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:842)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:592)
                                                                                                    	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:510)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:827)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@3e1f918, androidx.compose.ui.platform.MotionDurationScaleImpl@1ac8f71, StandaloneCoroutine{Cancelling}@c93b156, AndroidUiDispatcher@96ee5d7]
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by aabolfazl** [comment]
Could you share more detail? Code usage or happened scenario.

**Comment by kikoso** [comment]
@polivmi1 , can you provide a code snippet that you are using?

**Comment by polivmi1** [comment]
I missed the first message. Since that, we already restructured the logic to avoid this, so I don't have a reproducible sample but this happened when the map was loading before it fully loaded, onPause was called and then it was destroyed, so that map object didn't fully load internally and then it crashed when trying to clean some internal state that didn't exist.
