### ISSUE TITLE
NoSuchElementException: Collection contains no element matching the predicate. Error when items clustered.

### ISSUE THREAD

**Issue by Psijic** [googlemaps/android-maps-compose#317]
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...")
Maps
3. OS type and version
Android API 33 Emulator
4. Library version and other environment information
"com.google.maps.android:maps-compose:2.11.2"
"com.google.maps.android:maps-compose-utils:2.11.2"
#### Steps to reproduce
Add a lot of markers
Zoom in/out, make them clustering

#### Stack trace
```
 java.util.NoSuchElementException: Collection contains no element matching the predicate.
                 	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.onBeforeClusterItemRendered(ClusterRenderer.kt:236)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1022)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2300(DefaultClusterRenderer.java:992)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:709)
                 	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:678)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
```

**Comment by Psijic** [comment]
Found, it was fixed in 2.11.4. Can close then.
