### ISSUE TITLE
Clustering: ComposeUiClusterRenderer.renderViewToBitmapDescriptor fatal crash

### ISSUE THREAD

**Issue by andreas-umbricht** [googlemaps/android-maps-compose#325]
Hello everyone

Library version: maps-compose 2.11.4 and maps-compose-utils 2.11.4
Crashes happen on every Android version (minimum Android version of my app is 8) and across all types of devices.

I am not able to reproduce the error myself, but I can see the crashes in Crashlytics and they make up about 80% of all crashes in the app.

#### Code example

```
GoogleMap(
    uiSettings = MapUiSettings(zoomControlsEnabled = false, rotationGesturesEnabled = false),
    cameraPositionState = cameraPositionState,
    properties = MapProperties(
        mapStyleOptions = MapStyleOptions.loadRawResourceStyle(context, if (isSystemInDarkTheme()) R.raw.map_style_dark else R.raw.map_style_light),
        isMyLocationEnabled = false
    )
) {
    Clustering(
        items = favoriteItems,
        clusterContent = { cluster ->
            val averageTemperature = cluster
                .items
                .mapNotNull { it.weatherData?.observation?.getTemp() }
                .average()
                .toInt()
                .toString()

            val tempUnit = cluster
                .items
                .firstOrNull()
                ?.weatherData
                ?.observation
                ?.getTempUnit()

            TodayMarker(averageTemperature + tempUnit)
        },
        onClusterClick = {
            true
        },
        clusterItemContent = {
            TodayMarker(it.weatherData?.observation?.getFullTemperature())
        },
        onClusterItemClick = {
            true
        }
     )
}

@Composable
private fun TodayMarker(temperature: String?) {
    Text(
        text = temperature ?: "",
        fontWeight = FontWeight.SemiBold,
        fontSize = 20.dp,
        color = Color.White,
        modifier = Modifier
            .background(
                colorResource(id = R.color.dark_green),
                RoundedCornerShape(10.dp)
            )
            .border(
                BorderStroke(1.dp, colorResource(id = R.color.green)),
                RoundedCornerShape(10.dp)
            )
            .clip(RoundedCornerShape(10.dp))
            .padding(vertical = 1.dp, horizontal = 3.dp)
            .widthIn(min = 35.dp),
        textAlign = TextAlign.Center
    )
}
```

#### Stack trace
```
Fatal Exception: java.lang.IllegalArgumentException
width and height must be > 0
android.graphics.Bitmap.createBitmap (Bitmap.java:1118)
android.graphics.Bitmap.createBitmap (Bitmap.java:1085)
android.graphics.Bitmap.createBitmap (Bitmap.java:1035)
android.graphics.Bitmap.createBitmap (Bitmap.java:996)
com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.renderViewToBitmapDescriptor (ClusterRenderer.kt:171)
com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.onBeforeClusterItemRendered (ClusterRenderer.kt:157)
com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform (DefaultClusterRenderer.java:1022)
com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2300 (DefaultClusterRenderer.java:992)
com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask (DefaultClusterRenderer.java:707)
com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage (DefaultClusterRenderer.java:678)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loopOnce (Looper.java:226)
android.os.Looper.loop (Looper.java:313)
android.app.ActivityThread.main (ActivityThread.java:8757)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```

Is there currently some way to avoid this error?

Kind regards

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@andreas-umbricht Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by htooaunghlaing-cdg** [comment]
```
java.lang.IllegalArgumentException: width and height must be > 0
                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
                    	at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
                    	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.renderViewToBitmapDescriptor(ClusterRenderer.kt:171)
                    	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.onBeforeClusterItemRendered(ClusterRenderer.kt:157)
                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1022)
                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2300(DefaultClusterRenderer.java:992)
                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:707)
                    	at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:678)
                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                    	at android.os.Looper.loop(Looper.java:223)
                    	at android.app.ActivityThread.main(ActivityThread.java:7660)
                    	at java.lang.reflect.Method.invoke(Native Method)
                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

the cluster content : 
```
clusterContent = { cluster ->
                                    Surface(
                                        Modifier.size(40.dp),
                                        shape = CircleShape,
                                        color = Tertiary,
                                        contentColor = Color.White,
                                        border = BorderStroke(1.dp, Color.White),
                                    ) {
                                        Box(
                                            contentAlignment = Alignment.Center,

                                        ) {
                                            Text(
                                                "%,d".format(cluster.size),
                                                fontSize = 16.sp,
                                                fontWeight = FontWeight.Black,
                                                textAlign = TextAlign.Center,
                                            )
                                        }
                                    }
                                },
```

**Comment by jarg-147** [comment]
Same

Versions:
```
    implementation("com.google.maps.android:maps-compose:2.11.4")
    implementation("com.google.maps.android:maps-compose-utils:2.11.4")
```

Crash:

```
java.lang.IllegalArgumentException: width and height must be > 0
    android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
    android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
    android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
    android.graphics.Bitmap.createBitmap(Bitmap.java:991)
    com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.renderViewToBitmapDescriptor(ComposeUiClusterRenderer.java:59)
    com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.getDescriptorForCluster(ComposeUiClusterRenderer.java:95)
    com.google.maps.android.clustering.view.DefaultClusterRenderer.onBeforeClusterRendered(DefaultClusterRenderer.java:395)
    com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:395)
    com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:74)
    com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:28)
    android.os.Handler.dispatchMessage(Handler.java:107)
    android.os.Looper.loop(Looper.java:225)
    android.app.ActivityThread.main(ActivityThread.java:7564)

    java.lang.reflect.Method.invoke(Method.java:0)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)

```

Cluster:

```
clusterContent = { cluster ->
    Surface(
        modifier = Modifier.size(42.dp),
        shape = CircleShape,
        color = MaterialTheme.colorScheme.secondaryContainer,
        contentColor = MaterialTheme.colorScheme.onSecondaryContainer,
        border = BorderStroke(1.dp, MaterialTheme.colorScheme.onSecondaryContainer)
    ) {
        Box(contentAlignment = Alignment.Center) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.Center
            ) {
                Icon(
                    imageVector = Icons.Rounded.Pets,
                    contentDescription = "Dog Paw Icon",
                    modifier = Modifier.size(16.dp)
                )
                Text(
                    text = "%,d".format(cluster.size),
                    style = MaterialTheme.typography.labelSmall,
                    fontWeight = SemiBold
                )
            }
        }
    }
}
```

**Comment by andreas-umbricht** [comment]
@kikoso Yeah, your are correct. I am going to close this issue for now and track the progress in #297 
Thanks.
