### ISSUE TITLE
Unmanaged descriptor

### ISSUE THREAD

**Issue by Psijic** [googlemaps/android-maps-compose#332]
#### Environment details

1. Specify the API at the beginning of the title (for example, "Places: ...") - maps-compose, maps-compose-utils
3. OS type and version - Android API 33
4. Library version and other environment information - 2.11.4

#### Steps to reproduce

  1. Draw 1k+ items in clusters
  2. navigate to other screen
  3. navigate back and draw 1k+ items again

#### Stack trace
```
java.lang.IllegalArgumentException: Unmanaged descriptor
                   at com.google.maps.api.android.lib6.common.m.b(:com.google.android.gms.dynamite_mapsdynamite@232414047@23.24.14 (190800-0):0)
                   at com.google.maps.api.android.lib6.impl.w.c(:com.google.android.gms.dynamite_mapsdynamite@232414047@23.24.14 (190800-0):1)
                   at com.google.maps.api.android.lib6.impl.cw.u(:com.google.android.gms.dynamite_mapsdynamite@232414047@23.24.14 (190800-0):2)
                   at com.google.android.gms.maps.model.internal.p.bb(:com.google.android.gms.dynamite_mapsdynamite@232414047@23.24.14 (190800-0):50)
                   at m.ff.onTransact(:com.google.android.gms.dynamite_mapsdynamite@232414047@23.24.14 (190800-0):4)
                   at android.os.Binder.transact(Binder.java:1164)
                   at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
                   at com.google.android.gms.internal.maps.zzy.zzs(com.google.android.gms:play-services-maps@@18.1.0:3)
                   at com.google.android.gms.maps.model.Marker.setIcon(com.google.android.gms:play-services-maps@@18.1.0:2)
                   at com.google.maps.android.clustering.view.DefaultClusterRenderer.onClusterUpdated(DefaultClusterRenderer.java:937)
                   at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.perform(DefaultClusterRenderer.java:1053)
                   at com.google.maps.android.clustering.view.DefaultClusterRenderer$CreateMarkerTask.access$2300(DefaultClusterRenderer.java:992)
                   at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.performNextTask(DefaultClusterRenderer.java:709)
                   at com.google.maps.android.clustering.view.DefaultClusterRenderer$MarkerModifier.handleMessage(DefaultClusterRenderer.java:678)
```

**Comment by Psijic** [comment]
Looks like it happens when not all markers were drawn and you navigate to another screen.

**Comment by rizwan3742** [comment]
@kikoso @Psijic any workaround on this crash ?? I am also facing the same crash while navigating to next page in compose navigation by clicking on marker info window.

**Comment by max02100** [comment]
I've this bug too for more than 1k marker with custom icon

**Comment by rizwan3742** [comment]
@kikoso compsable function in the activity its works well. but when we have a complete app in jetpack compose. it crashes when we move from one composable function to another function.

**Comment by david-trujillo** [comment]
@kikoso I experience this when the marker has a custom icon

````
    val markerIcon = remember {
        mutableStateOf<BitmapDescriptor?>(null)
    }
    LaunchedEffect(Unit) {
        markerIcon.value = PoplerImages.Mark.toBitmap(context)?.let {
            BitmapDescriptorFactory.fromBitmap(it)
        }
    }
    
    ....
    
    GoogleMap(
    modifier = Modifier.fillMaxSize(),
    cameraPositionState = cameraPositionState,
    properties = mapProperties,
    uiSettings = mapUiSettings
) {
    Clustering(
        items = itemList,
        clusterContent = {
            Image(painter = painterResource(id = Icons.Mark))
        },
        clusterItemContent = {
            Image(painter = painterResource(id = Icons.Mark))
        }
    )
}
````

**Comment by david-trujillo** [comment]
@kikoso I experience this when the marker has a custom icon

````
    GoogleMap(
    modifier = Modifier.fillMaxSize(),
    cameraPositionState = cameraPositionState,
    properties = mapProperties,
    uiSettings = mapUiSettings
) {
    Clustering(
        items = itemList,
        clusterContent = {
            Image(painter = painterResource(id = Icons.Mark))
        },
        clusterItemContent = {
            Image(painter = painterResource(id = Icons.Mark))
        }
    )
}
````

**Comment by Psijic** [comment]
So, it's not completed but can't reproduce?

**Comment by JeevanRupacha** [comment]
I am having this crash because GoogleMap.clear()

**Comment by JeevanRupacha** [comment]
@kikoso GoogleMap(
            modifier = Modifier.fillMaxSize()
        ) {
            MapEffect(key1 = clusterItems) { map ->
                if (clusterItems.isNotEmpty()) {
                    val initialLatLng = getInitialCameraPosition(clusterItems)

                    //clear cached map and markers
                    clusterManager?.clearItems()
                    map.clear()
      }
}
by the way it's fixed now for me because I updated the dependency implementation "com.google.android.gms:play-services-maps:18.2.0" from version 18.1.0

**Comment by JeevanRupacha** [comment]
I had to do it because I am adding custom markers and creating cluster with dynamics marker items adding from backend . If I didn't use clear() the Cluster icon and marker overlap each other and don't form cluster
