### ISSUE TITLE
Clustering: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/widget/AppCompatTextView;

### ISSUE THREAD

**Issue by DarrylBayliss** [googlemaps/android-maps-compose#333]
#### Environment details

1. API: maps-compose-utils
2. Android 11 (Running on Motorola G8 Power)
3. Library Version: 2.11.4 

#### Steps to reproduce

  1. Setup an Android project with google maps library, google maps compose & google maps compose utils
  2. Create a GoogleMap, add a Clustering composable inside containing ClusterItems.
  3. Run the app, observe the app crashing on start.

#### Code example

```
        setContent {
            ComposeForMapsTheme {
                val hydePark = LatLng(51.508610, -0.163611)
                val regentsPark = LatLng(51.531143, -0.159893)
                val primroseHill = LatLng(51.539556, -0.16076088)

                val crystalPalacePark = LatLng(51.42153, -0.06749)
                val greenwichPark = LatLng(51.476688, 0.000130)
                val lloydPark = LatLng(51.364188, -0.080703)

                val cameraPositionState = rememberCameraPositionState {
                    position = CameraPosition.fromLatLngZoom(hydePark, 10f)
                }

                GoogleMap(
                    modifier = Modifier.fillMaxSize(),
                    cameraPositionState = cameraPositionState
                ) {

                    val parkMarkers = remember {
                        mutableStateListOf(
                            ParkItem(hydePark, "Hyde Park", "Marker in Hyde Park"),
                            ParkItem(regentsPark, "Regents Park", "Marker in Regents Park"),
                            ParkItem(primroseHill, "Primrose Hill", "Marker in Primrose Hill"),
                            ParkItem(
                                crystalPalacePark,
                                "Crystal Palace",
                                "Marker in Crystal Palace"
                            ),
                            ParkItem(greenwichPark, "Greenwich Park", "Marker in Greenwich Park"),
                            ParkItem(lloydPark, "Lloyd Park", "Marker in Lloyd Park"),
                        )
                    }

                    Clustering(items = parkMarkers,
                        onClusterClick = {
                            // Handle when the cluster is tapped
                            false
                        }, onClusterItemClick = { marker ->
                            // Handle when a marker in the cluster is tapped
                            false
                        })
                }
            }
        }
```

#### Stack trace
```
FATAL EXCEPTION: main
 Process: com.example.composeformaps, PID: 26199
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/widget/AppCompatTextView;
at com.google.maps.android.clustering.ClusterManager.<init>(ClusterManager.java:78)
at com.google.maps.android.clustering.ClusterManager.<init>(ClusterManager.java:70)
at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invokeSuspend(Clustering.kt:104)
at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invoke(Unknown Source:23)
at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invoke(Unknown Source:6)
at com.google.maps.android.compose.MapEffectKt$MapEffect$1.invokeSuspend(MapEffect.kt:26)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:250)
at android.app.ActivityThread.main(ActivityThread.java:7755)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@a187ca8, androidx.compose.runtime.BroadcastFrameClock@45873c1, StandaloneCoroutine{Cancelling}@5344766, AndroidUiDispatcher@3e7aaa7]
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.AppCompatTextView" on path: DexPathList[[dex file "/data/data/com.example.composeformaps/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~YdGQLEX1JnC1axCqYBw6-g==/com.example.composeformaps-ddPxnxXedmRy047TFrDueA==/base.apk"],nativeLibraryDirectories=[/data/app/~~YdGQLEX1JnC1axCqYBw6-g==/com.example.composeformaps-ddPxnxXedmRy047TFrDueA==/lib/arm64, /system/lib64, /system/system_ext/lib64, /product/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 18 more
```

Possible Solution:

Adding a dependency on AppCompat in the app module solves this crash. It seems like an oversight that I need to add this dependency explicitly.

```
implementation 'androidx.appcompat:appcompat:1.6.1'
```

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react with :+1: so we can see what is popular when we triage.
--------

@DarrylBayliss Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by DarrylBayliss** [comment]
I dug into this and the issue stems from google maps utils library. It uses a component called `SquareTextView`, which extends `AppCompatTextView`. 

The appcompat dependency isn't being provided for in my project and crashes. The crash doesn't appear when building the sample app in the repo.

**Comment by DarrylBayliss** [comment]
This is the same issue as https://github.com/googlemaps/android-maps-compose/issues/309

**Comment by wangela** [comment]
Thanks, closing this in favor of #309.
