### ISSUE TITLE
Lite mode compose map crash

### ISSUE THREAD

**Issue by tSquaredd** [googlemaps/android-maps-compose#387]
#### Environment details

Library versions
```kotlin
        object Maps {
            const val SDK = "com.google.android.gms:play-services-maps:18.1.0"
            const val KTX = "com.google.maps.android:maps-ktx:3.4.0"
            const val COMPOSE = "com.google.maps.android:maps-compose:2.14.0"
            const val UTILS = "com.google.maps.android:android-maps-utils:2.4.0"
        }
```

Crashing across multiple Android versions

#### Steps to reproduce
Not easily reproducible. Seems to occur somewhat randomly. 

#### Code example
This is what the Google map composable usage looks like
``` kotlin
GoogleMap(
                modifier = Modifier
                    .onGloballyPositioned {
                        if (!hasInitializedLayout && state.markerList.isNotEmpty()) {
                            scope.launch {
                                cameraPositionState.move(
                                    CameraUpdateFactory.newLatLngBounds(
                                        generateBoundsFromMarkerList(state.markerList),
                                        0
                                    )
                                )
                            }

                            hasInitializedLayout = true
                        }
                    },
                cameraPositionState = cameraPositionState,
                uiSettings = MapUiSettings(
                    compassEnabled = false,
                    indoorLevelPickerEnabled = false,
                    mapToolbarEnabled = false,
                    myLocationButtonEnabled = false,
                    rotationGesturesEnabled = false,
                    scrollGesturesEnabled = false,
                    scrollGesturesEnabledDuringRotateOrZoom = false,
                    tiltGesturesEnabled = false,
                    zoomControlsEnabled = false,
                    zoomGesturesEnabled = false
                ),
                googleMapOptionsFactory = {
                    GoogleMapOptions().liteMode(true)
                },
                properties = MapProperties(
                    mapStyleOptions = getMapTheme(LocalContext.current)
                ),
                onMapClick = {
                    onMapClicked()
                },
                onMapLoaded = {
                    isMapLoaded = true
                }
            ) {
                state.markerList.forEach { marker ->
                    Marker(
                        state = MarkerState(marker),
                        icon = bitmapDescriptor(
                            LocalContext.current,
                            R.drawable.ic_basket_stroked_18,
                            size = 75
                        ),
                        onClick = {
                            onMapClicked()
                            false
                        }
                    )
                }
            }
```

#### Stack trace
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'float com.google.maps.api.android.lib6.lite.n.a()' on a null object reference
                                                                                                    	at com.google.maps.api.android.lib6.lite.q.compare(:com.google.android.gms.policy_maps_core_dynamite@231710109@231710104065.542928491.542928491:2)
                                                                                                    	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
                                                                                                    	at java.util.TimSort.sort(TimSort.java:220)
                                                                                                    	at java.util.Arrays.sort(Arrays.java:1495)
                                                                                                    	at java.util.ArrayList.sort(ArrayList.java:1470)
                                                                                                    	at java.util.Collections.sort(Collections.java:206)
                                                                                                    	at com.google.maps.api.android.lib6.lite.l.onDraw(:com.google.android.gms.policy_maps_core_dynamite@231710109@231710104065.542928491.542928491:9)
                                                                                                    	at android.view.View.draw(View.java:23266)
                                                                                                    	at android.view.View.buildDrawingCacheImpl(View.java:22530)
                                                                                                    	at android.view.View.buildDrawingCache(View.java:22390)
                                                                                                    	at android.view.View.draw(View.java:22989)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22124)
                                                                                                    	at android.view.View.draw(View.java:22997)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22124)
                                                                                                    	at android.view.View.draw(View.java:22997)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
                                                                                                    	at android.view.View.draw(View.java:23269)
                                                                                                    	at androidx.compose.ui.platform.AndroidViewsHandler.drawView(AndroidViewsHandler.android.kt:72)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.drawAndroidView(AndroidComposeView.android.kt:829)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$coreModifier$2.invoke(AndroidViewHolder.android.kt:320)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidViewHolder$layoutNode$1$coreModifier$2.invoke(AndroidViewHolder.android.kt:317)
                                                                                                    	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:116)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:365)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
                                                                                                    	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
                                                                                                    	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:66)
                                                                                                    	at androidx.compose.material.ripple.AndroidRippleIndicationInstance.drawIndication(Ripple.android.kt:184)
                                                                                                    	at androidx.compose.foundation.IndicationModifier.draw(Indication.kt:183)
                                                                                                    	at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:349)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.performDraw(LayoutNodeDrawScope.kt:76)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:55)
                                                                                                    	at androidx.compose.foundation.BackgroundNode.draw(Background.kt:155)
2023-08-29 09:43:14.090 22175-22175 AndroidRuntime          com.xxxx          E  	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
                                                                                                    	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:365)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
                                                                                                    	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
                                                                                                    	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
                                                                                                    	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
                                                                                                    	at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
                                                                                                    	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:305)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1138)
                                                                                                    	at android.view.View.draw(View.java:23269)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22133)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
                                                                                                    	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
                                                                                                    	at android.view.View.updateDisplayListIfDirty(View.java:22089)
                                                                                                    	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
                                                                                                    	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
                                                                                                    	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
                                                                                                    	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4789)
2023-08-29 09:43:14.090 22175-22175 AndroidRuntime          com.xxxx          E  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4500)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3687)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:832)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Nothing within the stack trace points back to our application. Any help is appreciated.

**Comment by vpmalley** [comment]
If it may help, at this point in my investigation I noticed:
- it started happening after upgrading gradle (`com.android.tools.build:gradle`) from `8.0.2` to `8.1.0` and the firebase BoM from `32.2.0` to `32.2.2` (I couldn't find another change in the code that would be an obvious cause)
- in the sequence of map operations on the `MapView`, it's happening after adding markers and animating the camera using LatLngBounds and a padding

**Comment by arcao** [comment]
FYI. This crash happens in old XML views too. Probably bug in Map SDK.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float com.google.maps.api.android.lib6.lite.n.a()' on a null object reference
       at com.google.maps.api.android.lib6.lite.q.compare(:com.google.android.gms.policy_maps_core_dynamite@231710109@231710104065.542928491.542928491:2)
       at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
       at java.util.TimSort.sort(TimSort.java:220)
       at java.util.Arrays.sort(Arrays.java:1495)
       at java.util.ArrayList.sort(ArrayList.java:1470)
       at java.util.Collections.sort(Collections.java:206)
       at com.google.maps.api.android.lib6.lite.l.onDraw(:com.google.android.gms.policy_maps_core_dynamite@231710109@231710104065.542928491.542928491:9)
       at android.view.View.draw(View.java:24406)
       at android.view.View.buildDrawingCacheImpl(View.java:23664)
       at android.view.View.buildDrawingCache(View.java:23524)
       at android.view.View.draw(View.java:24128)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.draw(View.java:24409)
       at android.view.View.updateDisplayListIfDirty(View.java:23267)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5545)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.draw(View.java:24409)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4944)
       at android.view.View.updateDisplayListIfDirty(View.java:23267)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.draw(View.java:24409)
       at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:2324)
       at android.view.View.updateDisplayListIfDirty(View.java:23267)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
       at android.view.View.draw(View.java:24409)
       at android.view.View.updateDisplayListIfDirty(View.java:23267)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at android.view.View.updateDisplayListIfDirty(View.java:23253)
       at android.view.View.draw(View.java:24136)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
       at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1540)
       at android.view.View.draw(View.java:24409)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1513)
       at android.view.View.updateDisplayListIfDirty(View.java:23267)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:777)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:783)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:881)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:5647)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by vpmalley** [comment]
Thank you @kikoso
I filed [a bug there](https://issuetracker.google.com/issues/302010432)
