### ISSUE TITLE
When open screen app close with Resources$NotFoundException error

### ISSUE THREAD

**Issue by YellowPantherDeveloper** [googlemaps/android-maps-compose#402]
**I used below google maps dependency**

implementation("com.google.maps.android:maps-compose:2.7.2")
implementation("com.google.android.gms:play-services-maps:18.1.0")

**Code**

import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import com.app.plaisports.R
import com.app.plaisports.common.generateSmallIcon
import com.app.plaisports.common.safeLaunch
import com.app.plaisports.utils.openGoogleMap
import com.google.android.gms.maps.CameraUpdateFactory
import com.google.android.gms.maps.model.BitmapDescriptorFactory
import com.google.android.gms.maps.model.CameraPosition
import com.google.android.gms.maps.model.LatLng
import com.google.android.gms.maps.model.MapStyleOptions
import com.google.maps.android.compose.GoogleMap
import com.google.maps.android.compose.MapProperties
import com.google.maps.android.compose.MapUiSettings
import com.google.maps.android.compose.Marker
import com.google.maps.android.compose.MarkerState
import com.google.maps.android.compose.rememberCameraPositionState

@Composable
fun LocationMap(
    latLang: LatLng,
    title: String?,
    id: String?,
) {
    val scope = rememberCoroutineScope()
    val context = LocalContext.current
    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(latLang, 12F)
    }

    GoogleMap(
        modifier = Modifier.fillMaxSize(),
        cameraPositionState = cameraPositionState,
        properties = MapProperties(
            mapStyleOptions = MapStyleOptions.loadRawResourceStyle(
                context,
                R.raw.style
            ),
            isMyLocationEnabled = false,
        ),
        uiSettings = MapUiSettings(
            compassEnabled = false,
            mapToolbarEnabled = false,
            myLocationButtonEnabled = false,
            zoomControlsEnabled = false,
            rotationGesturesEnabled = false,
            scrollGesturesEnabled = false,
            scrollGesturesEnabledDuringRotateOrZoom = false,
            tiltGesturesEnabled = false,
            zoomGesturesEnabled = false
        ),
        onMapClick = {
            openGoogleMap(context, latLang)
        }
    ) {
        scope.safeLaunch {
            val cameraPositionBuilder = CameraPosition.builder()
            cameraPositionBuilder.target(latLang)
            cameraPositionBuilder.zoom(12F)
            cameraPositionState.animate(
                update = CameraUpdateFactory.newCameraPosition(
                    cameraPositionBuilder.build()
                ),
                durationMs = 1000
            )
        }
        Marker(
            state = MarkerState(position = latLang),
            title = "",
            icon = BitmapDescriptorFactory.fromBitmap(
                generateSmallIcon(
                    context,
                    R.drawable.ic_map_marker_sel
                )
            ),
            onClick = {
                openGoogleMap(context, latLang)
                false
            }
        )
    }
}

--

**Below android runtime exception found on google map screen open** 

FATAL EXCEPTION: main Process: com.app.plaisports, PID: 6727 android.content.res.Resources$NotFoundException: Drawable com.app.plaisports:drawable/$mtrl_switch_thumb_pressed_checked__0 with resource ID #0x7f080022 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@97525c8, androidx.compose.ui.platform.MotionDurationScaleImpl@9143661, StandaloneCoroutine{Cancelling}@632e586, AndroidUiDispatcher@13ebe47] Caused by: android.content.res.Resources$NotFoundException: File res/drawable/$mtrl_switch_thumb_pressed_checked__0.xml from drawable resource ID #0x7f080022
at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:943)
at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:726)
at android.content.res.Resources.loadDrawable(Resources.java:1014)
at android.content.res.Resources.getDrawableForDensity(Resources.java:1004)
at android.content.res.Resources.getDrawable(Resources.java:943)
at android.content.res.Resources.getDrawable(Resources.java:918)
at com.google.maps.api.android.lib6.impl.ay.n(:com.google.android.gms.dynamite_mapsdynamite@233414044@23.34.14 (190400-0):41)
at com.google.maps.api.android.lib6.impl.x.<init>(:com.google.android.gms.dynamite_mapsdynamite@233414044@23.34.14 (190400-0):98)
at com.google.maps.api.android.lib6.impl.bk.aD(:com.google.android.gms.dynamite_mapsdynamite@233414044@23.34.14 (190400-0):30)
at com.google.maps.api.android.lib6.impl.cu.d(:com.google.android.gms.dynamite_mapsdynamite@233414044@23.34.14 (190400-0):11)
at com.google.android.gms.maps.internal.q.bb(:com.google.android.gms.dynamite_mapsdynamite@233414044@23.34.14 (190400-0):159)
at m.fi.onTransact(:com.google.android.gms.dynamite_mapsdynamite@233414044@23.34.14 (190400-0):21)
at android.os.Binder.transact(Binder.java:1084)
at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
at com.google.android.gms.maps.internal.zzl.onCreate(com.google.android.gms:play-services-maps@@18.1.0:3)
at com.google.android.gms.maps.zzag.onCreate(com.google.android.gms:play-services-maps@@18.1.0:3)
at com.google.android.gms.dynamic.zac.zab(com.google.android.gms:play-services-base@@18.0.1:1)
at com.google.android.gms.dynamic.zaa.onDelegateCreated(com.google.android.gms:play-services-base@@18.0.1:3)
at com.google.android.gms.maps.zzah.zzb(com.google.android.gms:play-services-maps@@18.1.0:5)
at com.google.android.gms.maps.zzah.createDelegate(com.google.android.gms:play-services-maps@@18.1.0:1)
at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.0.1:6)
at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@18.0.1:1)
at com.google.android.gms.maps.MapView.onCreate(com.google.android.gms:play-services-maps@@18.1.0:4)
at com.google.maps.android.compose.GoogleMapKt.lifecycleObserver$lambda-11(GoogleMap.kt:193)
at com.google.maps.android.compose.GoogleMapKt.$r8$lambda$ml76XdpXTOPqW4q28tKk_7GmLZk(Unknown Source:0)
at com.google.maps.android.compose.GoogleMapKt$$ExternalSyntheticLambda0.onStateChanged(Unknown Source:4)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:203)
at com.google.maps.android.compose.GoogleMapKt$MapLifecycle$1.invoke(GoogleMap.kt:172)
at com.google.maps.android.compose.GoogleMapKt$MapLifecycle$1.invoke(GoogleMap.kt:168)
at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:81)
at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1091)
at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:587)
at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:505)
at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1230)
at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
at android.view.Choreographer.doFrame(Choreographer.java:925)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) Caused by: android.view.InflateException: Class not found objectAnimator
at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:225)
at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1400)
at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1359)
at android.content.res.ResourcesImpl.loadXmlDrawable(ResourcesImpl.java:975)
at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:927)

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react on the original post above with :+1: so we can see what is popular when we triage.
--------

@YellowPantherDeveloper Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._
