### ISSUE TITLE
Resources NotFoundException

### ISSUE THREAD

**Issue by Psijic** [googlemaps/android-maps-compose#418]
```
Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x7f080055
       at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:224)
       at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
       at android.content.res.XResources.getDrawableForDensity(XResources.java:868)
       at android.content.res.Resources.getDrawable(Resources.java:819)
       at android.content.res.XResources.getDrawable(XResources.java:790)
       at android.content.Context.getDrawable(Context.java:605)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:11)
       at com.google.maps.android.ui.BubbleDrawable.<init>(BubbleDrawable.java:11)
       at com.google.maps.android.ui.IconGenerator.<init>(IconGenerator.java:5)
       at com.google.maps.android.clustering.view.DefaultClusterRenderer.<init>(DefaultClusterRenderer.java:69)
       at com.google.maps.android.clustering.ClusterManager.<init>(ClusterManager.java:35)
       at com.google.maps.android.clustering.ClusterManager.<init>(ClusterManager.java:35)
       at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invokeSuspend(Clustering.kt:464)
       at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invoke(Clustering.kt:70)
       at com.google.maps.android.compose.clustering.ClusteringKt$rememberClusterManager$1.invoke(Clustering.kt:70)
       at com.google.maps.android.compose.MapEffectKt$MapEffect$1.invokeSuspend(MapEffect.kt:34)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:8)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:109)
       at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.java:22)
       at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.java:22)
       at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.java:2)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
Code:
```
    val events by viewModel.eventsLocalDto.filtered.collectAsStateWithLifecycle()
    val selectedEvent by viewModel.selectedEvent.collectAsStateWithLifecycle()

    Clustering(
        items = events,
        onClusterItemClick = {
            Timber.v("Marker clicked: ${it.name}")
            viewModel.selectEvent(it)
            true
        },
    )

    if (selectedEvent is EventItem) (selectedEvent as EventItem).latLng.let {
        val selectedMarker = BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE)
        Marker(state = MarkerState(it), zIndex = 0.5f, icon = selectedMarker)
    }
```
Maps version: 2.15.0
Model: Nexus 5X, Android 8.1.0

**Comment by Psijic** [comment]
This is the file using Google Maps:
```
@ExperimentalPermissionsApi
@MapsComposeExperimentalApi
@RequiresPermission(anyOf = [Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION])
@ExperimentalCoroutinesApi
@Composable
fun GoogleMapContainer(viewModel: MapViewModel, mapBundle: MapBundle) {
    GoogleMapView(viewModel = viewModel,
        mapBundle = mapBundle,
        onMapClick = { mapBundle.onMapClick() },
        content = { GoogleMapCluster(viewModel) })
}

@Composable
private fun GoogleMapView(
    isMyLocationEnabled: Boolean,
    cameraPositionState: CameraPositionState,
    onMapLoaded: () -> Unit,
    onMapClick: (LatLng) -> Unit,
    content: @Composable (() -> Unit)?
) {
    Timber.v("Start GoogleMap")

    val mapProperties = remember {
        MapProperties(
            maxZoomPreference = Config.Map.ZOOM_MAX,
            minZoomPreference = Config.Map.ZOOM_MIN,
            isMyLocationEnabled = isMyLocationEnabled
        )
    }

    val uiSettings =
        MapUiSettings(myLocationButtonEnabled = false, mapToolbarEnabled = false, zoomControlsEnabled = false)

    GoogleMap(
        Modifier.fillMaxSize(),
        properties = mapProperties,
        cameraPositionState = cameraPositionState,
        uiSettings = uiSettings,
        onMapLoaded = onMapLoaded,
        onMapClick = onMapClick,
        content = content
    )
}

@ExperimentalCoroutinesApi
@MapsComposeExperimentalApi
@Composable
private fun GoogleMapCluster(viewModel: MapViewModel) {
    Timber.v("GoogleMapCluster")

    val focusManager = LocalFocusManager.current
    val events by viewModel.eventsLocalDto.filtered.collectAsStateWithLifecycle()
    val selectedEvent by viewModel.selectedEvent.collectAsStateWithLifecycle()

    Clustering(
        items = events,
        onClusterItemClick = {
            Timber.v("Marker clicked: ${it.name}")
            viewModel.selectEvent(it)
            viewModel.setUiVisible(true)
            focusManager.clearFocus()
            true
        },
    )

    if (selectedEvent is EventItem) (selectedEvent as EventItem).latLng.let {
        val selectedMarker = BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE)
        Marker(state = MarkerState(it), zIndex = 0.5f, icon = selectedMarker)
    }
}

@ExperimentalPermissionsApi
@ExperimentalCoroutinesApi
@Composable
private fun GoogleMapView(
    viewModel: MapViewModel,
    mapBundle: MapBundle,
    onMapClick: (LatLng) -> Unit = {},
    onMapLoaded: () -> Unit = {},
    content: @Composable (() -> Unit)
) {
    Timber.v("Start MapViewContainer")

    val coroutineScope = rememberCoroutineScope()
    val cameraPosition by viewModel.cameraPosition.collectAsStateWithLifecycle()
    val updateMapLocation by viewModel.updateMapLocation.collectAsStateWithLifecycle()

    val cameraPositionState = rememberCameraPositionState {
        position = CameraPosition.fromLatLngZoom(cameraPosition.location, cameraPosition.zoom)
    }

    if (updateMapLocation) {
        cameraPositionState.position = CameraPosition.fromLatLngZoom(cameraPosition.location, cameraPosition.zoom)
        viewModel.setUpdateMapLocation(false)
    }

    mapBundle.locationProceedAction = { latLng ->
        coroutineScope.launch {
            cameraPositionState.animate(CameraUpdateFactory.newLatLngZoom(latLng, cameraPosition.zoom))
        }
    }

    LaunchedEffect(cameraPosition.zoom) { cameraPositionState.animate(CameraUpdateFactory.zoomTo(cameraPosition.zoom)) }

    LaunchedEffect(cameraPositionState.isMoving) {
        if (!cameraPositionState.isMoving) {
            with(cameraPositionState.position) {
                Timber.d("cameraPositionState, setMapLocation")
                viewModel.setCameraPosition(target.latitude, target.longitude, zoom)
            }
        }
    }

    GoogleMapView(
        mapBundle.locationPermissionsState.allPermissionsGranted, cameraPositionState, onMapLoaded, onMapClick, content
    )
}
```

**Comment by Psijic** [comment]
I got this error from Firebase Crashlytics. Currently I can't share the project, sorry.

**Comment by jsselle** [comment]
fwiw I am getting this bug too. I cannot legally share project, and the issue seems to be quite sporadic on my case.

**Comment by barath-dev** [comment]
Even i am encountering similar kind of issues, 

android.content.res.Resources$NotFoundException: Resource ID #0x7f0702e9 type #0x4 is not valid
                                                                                                    	at android.content.res.Resources.getDimensionPixelSize(Resources.java:836)
                                                                                                    	at com.google.maps.api.android.lib6.impl.be.d(:com.google.android.gms.policy_maps_core_dynamite@234910201@234910200049.587833741.587833741:41)
                                                                                                    	at com.google.maps.api.android.lib6.impl.ab.<init>(:com.google.android.gms.policy_maps_core_dynamite@234910201@234910200049.587833741.587833741:65)
                                                                                                    	at com.google.maps.api.android.lib6.impl.ck.aE(:com.google.android.gms.policy_maps_core_dynamite@234910201@234910200049.587833741.587833741:29)
                                                                                                    	at com.google.maps.api.android.lib6.impl.dn.p(:com.google.android.gms.policy_maps_core_dynamite@234910201@234910200049.587833741.587833741:21)
                                                                                                    	at com.google.android.gms.maps.internal.q.bp(:com.google.android.gms.policy_maps_core_dynamite@234910201@234910200049.587833741.587833741:226)
                                                                                                    	at m.bay.onTransact(:com.google.android.gms.policy_maps_core_dynamite@234910201@234910200049.587833741.587833741:21)
                                                                                                    	at android.os.Binder.transact(Binder.java:1164)
                                                                                                    	at com.google.android.gms.internal.maps.zza.zzJ(com.google.android.gms:play-services-maps@@18.2.0:2)
                                                                                                    	at com.google.android.gms.maps.internal.zzk.onCreateView(com.google.android.gms:play-services-maps@@18.2.0:5)
                                                                                                    	at com.google.android.gms.maps.zzav.onCreateView(com.google.android.gms:play-services-maps@@18.2.0:7)
                                                                                                    	at com.google.android.gms.dynamic.zad.zab(com.google.android.gms:play-services-base@@18.3.0:2)
                                                                                                    	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.3.0:1)
                                                                                                    	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreateView(com.google.android.gms:play-services-base@@18.3.0:2)
                                                                                                    	at com.google.android.gms.maps.SupportMapFragment.onCreateView(com.google.android.gms:play-services-maps@@18.2.0:1)
                                                                                                    	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8330)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
