### ISSUE TITLE
Google maps crash not on the main thread

### ISSUE THREAD

**Issue by barry-irvine** [googlemaps/android-maps-compose#462]
Please be sure to include as much information as possible:

#### Environment details

On our Firebase Test Lab device I've witnessed the below stacktrace. In the video I couldn't even see the Compose map on the screen so it may have been caused by the teardown of the previous test or something. This is doesn't happen on every test run and is just a cause of flakiness.

This is just running on the default Pixel 5 Android 30 emulator.
We are on Compose Maps 4.3.0

#### Steps to reproduce

Unsure

#### Code example

Map not showing at moment of crash anyway, so not sure what to show as the example.

#### Stack trace
```
com.google.maps.api.android.lib6.common.apiexception.c: Not on the main thread
	at com.google.maps.api.android.lib6.common.p.g(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:8)
	at com.google.maps.api.android.lib6.common.v.a(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:15)
	at com.google.maps.api.android.lib6.impl.cj.s(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:3)
	at com.google.android.gms.maps.internal.k.bp(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:344)
	at m.bbc.onTransact(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:21)
	at android.os.Binder.transact(Binder.java:1043)
	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.2.0:2)
	at com.google.android.gms.maps.internal.zzg.clear(com.google.android.gms:play-services-maps@@18.2.0:2)
	at com.google.android.gms.maps.GoogleMap.clear(com.google.android.gms:play-services-maps@@18.2.0:1)
	at com.google.maps.android.compose.MapApplier.onClear(MapApplier.kt:46)
	at androidx.compose.runtime.AbstractApplier.clear(Applier.kt:213)
	at androidx.compose.runtime.CompositionImpl.dispose(Composition.kt:625)
	at com.google.maps.android.compose.GoogleMapKt$GoogleMap$4.invokeSuspend(GoogleMap.kt:289)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at androidx.compose.ui.test.ApplyingContinuationInterceptor$SendApplyContinuation.resumeWith(ApplyingContinuationInterceptor.kt:65)
	at androidx.compose.ui.test.FrameDeferringContinuationInterceptor$FrameDeferredContinuation.resumeWith(FrameDeferringContinuationInterceptor.kt:194)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:217)
	at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:224)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1450)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:799)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:759)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:675)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:641)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1439)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:904)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
	at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:700)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:641)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1439)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1477)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:904)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
	at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:700)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.childCancelled(JobSupport.kt:655)
	at kotlinx.coroutines.ChildHandleNode.childCancelled(JobSupport.kt:1440)
	at kotlinx.coroutines.JobSupport.cancelParent(JobSupport.kt:360)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:334)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:904)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:832)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:270)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at androidx.compose.ui.test.ApplyingContinuationInterceptor$SendApplyContinuation.resumeWith(ApplyingContinuationInterceptor.kt:65)
	at androidx.compose.ui.test.FrameDeferringContinuationInterceptor$FrameDeferredContinuation.resumeWith(FrameDeferringContinuationInterceptor.kt:194)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1.invoke(Recomposer.kt:933)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$unregisterApplyObserver$1.invoke(Recomposer.kt:927)
	at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1824)
	at androidx.compose.runtime.snapshots.SnapshotKt.advanceGlobalSnapshot(Snapshot.kt:1839)
	at androidx.compose.runtime.snapshots.SnapshotKt.access$advanceGlobalSnapshot(Snapshot.kt:1)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.sendApplyNotifications(Snapshot.kt:583)
	at androidx.compose.ui.test.ApplyingContinuationInterceptor$SendApplyContinuation.resumeWith(ApplyingContinuationInterceptor.kt:66)
	at androidx.compose.ui.test.FrameDeferringContinuationInterceptor$FrameDeferredContinuation.resumeWith(FrameDeferringContinuationInterceptor.kt:194)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:590)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2896)
	at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:638)
	at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:458)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:36)
	at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:3089)
	at kotlinx.coroutines.channels.BufferedChannel.send(Unknown Source:0)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2$1$1.emit(Combine.kt:32)
	at com.gocitypass.core.extensions.FlowExtensionKt$mapWhenNotNull$$inlined$map$1$2.emit(Emitters.kt:223)
	at com.gocitypass.storage.repo.LocalAttractionRepositoryImpl$getDetailedAttractionById$$inlined$map$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at androidx.compose.ui.test.ApplyingContinuationInterceptor$SendApplyContinuation.resumeWith(ApplyingContinuationInterceptor.kt:65)
	at androidx.compose.ui.test.FrameDeferringContinuationInterceptor$FrameDeferredContinuation.resumeWith(FrameDeferringContinuationInterceptor.kt:194)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:590)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(BufferedChannel.kt:2896)
	at kotlinx.coroutines.channels.BufferedChannelKt.access$tryResume0(BufferedChannel.kt:1)
	at kotlinx.coroutines.channels.BufferedChannel$BufferedChannelIterator.tryResumeHasNext(BufferedChannel.kt:1689)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(BufferedChannel.kt:642)
	at kotlinx.coroutines.channels.BufferedChannel.updateCellSend(BufferedChannel.kt:458)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(BufferedChannel.kt:36)
	at kotlinx.coroutines.channels.BufferedChannel.send$suspendImpl(BufferedChannel.kt:3089)
	at kotlinx.coroutines.channels.BufferedChannel.send(Unknown Source:0)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:130)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: com.google.maps.api.android.lib6.common.apiexception.c: Not on the main thread
		at com.google.maps.api.android.lib6.common.p.g(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:8)
		at com.google.maps.api.android.lib6.common.v.a(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:15)
		at com.google.maps.api.android.lib6.impl.cj.aa(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:7)
		at com.google.android.gms.maps.internal.k.bp(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:83)
		at m.bbc.onTransact(:com.google.android.gms.policy_maps_core_dynamite@233012105@233012102065.561947648.561947648:21)
		at android.os.Binder.transact(Binder.java:1043)
		at com.google.android.gms.internal.maps.zza.zzJ(com.google.android.gms:play-services-maps@@18.2.0:2)
		at com.google.android.gms.maps.internal.zzg.setMapStyle(com.google.android.gms:play-services-maps@@18.2.0:3)
		at com.google.android.gms.maps.GoogleMap.setMapStyle(com.google.android.gms:play-services-maps@@18.2.0:1)
		at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$2$10.invoke(MapUpdater.kt:156)
		at com.google.maps.android.compose.MapUpdaterKt$MapUpdater$2$10.invoke(MapUpdater.kt:156)
		at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1712)
		at androidx.compose.runtime.ComposerImpl$apply$operation$1.invoke(Composer.kt:1710)
		at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:818)
		at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:849)
		at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:625)
		at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:537)
		at androidx.compose.ui.test.TestMonotonicFrameClock$withFrameNanos$2$1$1.invoke(TestMonotonicFrameClock.jvm.kt:104)
		at androidx.compose.ui.test.TestMonotonicFrameClock$withFrameNanos$2$1$1.invoke(TestMonotonicFrameClock.jvm.kt:103)
		at androidx.compose.ui.test.TestMonotonicFrameClock$performFrame$1.invoke(TestMonotonicFrameClock.jvm.kt:149)
		at androidx.compose.ui.test.TestMonotonicFrameClock$performFrame$1.invoke(TestMonotonicFrameClock.jvm.kt:132)
		at androidx.compose.ui.test.FrameDeferringContinuationInterceptor.runWithoutResumingCoroutines(FrameDeferringContinuationInterceptor.kt:60)
		at androidx.compose.ui.test.TestMonotonicFrameClock.performFrame(TestMonotonicFrameClock.jvm.kt:132)
		at androidx.compose.ui.test.TestMonotonicFrameClock.access$performFrame(TestMonotonicFrameClock.jvm.kt:53)
		at androidx.compose.ui.test.TestMonotonicFrameClock$withFrameNanos$2$1$2.invokeSuspend(TestMonotonicFrameClock.jvm.kt:110)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
		at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
		at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
		at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
		at androidx.compose.ui.test.TestMonotonicFrameClock.withFrameNanos(TestMonotonicFrameClock.jvm.kt:108)
		at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:537)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 58 more
	[CIRCULAR REFERENCE:com.google.maps.api.android.lib6.common.apiexception.c: Not on the main thread]

    
```

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react on the original post above with :+1: so we can see what is popular when we triage.
--------

@barry-irvine Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._
