### ISSUE TITLE
Google map (SupportMapFragment) crash on backpress.

### ISSUE THREAD

**Issue by mintheinwin** [googlemaps/android-maps-compose#494]
I created a tab view featuring three tabs, one of which is dedicated to a Map view. The problem occurs when the device doesn't have a SIM card or lacks internet access. The app crashes when attempting to navigate back, especially when the map is unavailable.

    implementation 'com.google.android.gms:play-services-maps:18.2.0'
    // implementation 'com.google.android.libraries.places:places:3.2.0'
    implementation 'com.google.android.gms:play-services-location:21.0.1'

In xlm fragment layout 

            <RelativeLayout
                android:id="@+id/rl_map"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@+id/spinner_chemical_option"
                android:paddingLeft="@dimen/spacing_normal"
                android:paddingTop="@dimen/spacing_normal"
                android:paddingRight="@dimen/padding_small"
                android:visibility="visible">

                <fragment
                    android:id="@+id/map"
                    class="com.google.android.gms.maps.SupportMapFragment"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/map_height"
                    android:layout_marginTop="@dimen/spacing_micro" />
            </RelativeLayout>

            <RelativeLayout
                android:id="@+id/rl_require_sim_card"
                android:visibility="gone"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_below="@+id/rl_map"
                android:paddingLeft="@dimen/spacing_normal"
                android:paddingTop="@dimen/spacing_normal"
                android:paddingRight="@dimen/padding_small">

                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:gravity="center"
                    android:text="@string/require_sim_card"
                    android:textColor="@color/rejected"
                    android:textSize="@dimen/app_text_size_medium_material"
                    android:textStyle="normal" />
            </RelativeLayout>

in fragment class

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle   savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_data_map, container, false);
        ButterKnife.bind(this, view);
        iv_view_color_setting.setOnClickListener(this);

        // Build the map.
        supportMapFragment = (SupportMapFragment) getChildFragmentManager().findFragmentById(R.id.map);
        supportMapFragment.getMapAsync(this);

        boolean sim = UtilData.isSimAvailable(getActivity());
        if (sim){
            rl_map.setVisibility(View.VISIBLE);
            rl_require_sim_card.setVisibility(View.GONE);
        }else {
            rl_map.setVisibility(View.GONE);
            rl_require_sim_card.setVisibility(View.VISIBLE);
        }

    @Override
    public void onStart() {
        super.onStart();
        supportMapFragment.onStart();
        //Register eventBus to get Subscribe data
        if (!EventBus.getDefault().isRegistered(this)) {
            EventBus.getDefault().register(this);
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        supportMapFragment.onResume();
        startLocationUpdates();
    }

    @Override
    public void onPause() {
        super.onPause();
        supportMapFragment.onPause();
        fusedLocationProviderClient.removeLocationUpdates(locationCallback);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
    supportMapFragment.onDestroy();
    }

    @Override
     public void onDestroyView() {
         super.onDestroyView();
         supportMapFragment.onDestroyView();
     } 
    }

Error Log

   E  FATAL EXCEPTION: main
                                                                                                    Process: com.dso.chemproxc2, PID: 31482
                                                                                                    java.lang.RuntimeException: Unable to destroy activity {com.dso.chemproxc2/com.dso.chemproxc2.activity.DataAcquiringActivity}: java.lang.RuntimeException: java.lang.InterruptedException
                                                                                                    	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
                                                                                                    	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
                                                                                                    	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.RuntimeException: java.lang.InterruptedException
                                                                                                    	at m.dzl.h(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:52)
                                                                                                    	at com.google.maps.api.android.lib6.phoenix.av.l(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:287)
                                                                                                    	at com.google.maps.api.android.lib6.impl.cm.w(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:135)
                                                                                                    	at com.google.maps.api.android.lib6.impl.dp.e(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:6)
                                                                                                    	at com.google.android.gms.maps.internal.q.bp(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:141)
                                                                                                    	at m.bcb.onTransact(:com.google.android.gms.policy_maps_core_dynamite@234210305@234210302065.578192611.578192611:21)
                                                                                                    	at android.os.Binder.transact(Binder.java:1200)
                                                                                                    	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.2.0:2)
                                                                                                    	at com.google.android.gms.maps.internal.zzk.onDestroy(com.google.android.gms:play-services-maps@@18.2.0:2)
                                                                                                    	at com.google.android.gms.maps.zzav.onDestroy(com.google.android.gms:play-services-maps@@18.2.0:1)
                                                                                                    	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onDestroy(com.google.android.gms:play-services-base@@18.1.0:1)
                                                                                                    	at com.google.android.gms.maps.SupportMapFragment.onDestroy(com.google.android.gms:play-services-maps@@18.2.0:1)
                                                                                                    	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3376)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:811)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2988)
                                                                                                    	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3371)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:811)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2988)

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react on the original post above with :+1: so we can see what is popular when we triage.
--------

@mintheinwin Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._
