### ISSUE TITLE
Black lines showing instead of streets in Android 14 UpsideDownCake

### ISSUE THREAD

**Issue by spss20** [googlemaps/android-maps-compose#555]
<img width="1213" alt="image" src="https://github.com/googlemaps/android-maps-compose/assets/29224720/27e1d967-3c48-4ebc-8f8d-84c3581ff283">

#### Environment details

1. Map Compose
2. Android 14 UpsideDownCake
3. Version: 4.3.3

#### Steps to reproduce

  1. Run a simple Google Map composable to display map in any Android 14 emulator.
  2. You will see black lines for streets as you zoom in. 

### Device Logs Below

2024-04-18 16:46:00.901  9331-9331  DynamiteModule          com.map.example              I  Considering local module com.google.android.gms.maps_core_dynamite:0 and remote module com.google.android.gms.maps_core_dynamite:203115000
2024-04-18 16:46:00.907  9331-9331  DynamiteModule          com.map.example              I  Selected remote version of com.google.android.gms.maps_core_dynamite, version >= 203115000
2024-04-18 16:46:00.951  9331-9331  ziparchive              com.map.example              W  Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000000e/MapsDynamite.dm': No such file or directory
2024-04-18 16:46:00.953  9331-9331  ziparchive              com.map.example              W  Unable to open '/data/user_de/0/com.google.android.gms/app_chimera/m/0000000e/MapsDynamite.dm': No such file or directory
2024-04-18 16:46:01.000  9331-9331  Google Maps Android API com.map.example              I  Google Play services client version: 18020000
2024-04-18 16:46:01.026  9331-9331  Google Maps Android API com.map.example              I  Google Play services package version: 231818044
2024-04-18 16:46:01.026  9331-9331  Google Maps Android API com.map.example              I  Google Play services maps renderer version(legacy): 203115000
2024-04-18 16:46:01.134  9331-9331  Google Maps Android API com.map.example              I  Google Play services package version: 231818044
2024-04-18 16:46:01.134  9331-9331  Google Maps Android API com.map.example              I  Google Play services maps renderer version(legacy): 203115000
2024-04-18 16:46:03.228  9331-9359  MobStoreFlagStore       com.map.example              W  Unable to update local snapshot for com.google.android.libraries.consentverifier#com.map.example, may result in stale flags.
                                                                                                    java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.map.example, sha256=[c54e4a41a05ee5ff20df0303ddef95466175ab365cf10717828b8e14ebbaccfe], atk=true, ver=231818044.true (go/gsrlt)
                                                                                                    	at ajs.s(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):3)
                                                                                                    	at ajs.get(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
                                                                                                    	at alc.g(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
                                                                                                    	at yz.c(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):1)
                                                                                                    	at zb.run(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):0)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.map.example, sha256=[c54e4a41a05ee5ff20df0303ddef95466175ab365cf10717828b8e14ebbaccfe], atk=true, ver=231818044.true (go/gsrlt)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3041)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3024)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2966)
                                                                                                    	at fe.c(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
                                                                                                    	at rx.a(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):4)
                                                                                                    	at jl.e(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
                                                                                                    	at kj.t(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
                                                                                                    	at kj.u(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):3)
                                                                                                    	at kj.e(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):2)
                                                                                                    	at kn.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@231818044@23.18.18 (190400-0):78)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react on the original post above with :+1: so we can see what is popular when we triage.
--------

@spss20 Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by spss20** [comment]
@kikoso Yes, you were right , I tested in real Android 14 device, it didn't happen. It is only happening in Android 14 emulator
