### ISSUE TITLE
Crash `com.google.maps.api.android.lib6.phoenix.cv.d`

### ISSUE THREAD

**Issue by aritra-tech** [googlemaps/android-maps-compose#560]
Fatal Exception: java.lang.ClassCastException
java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode

Crash Log
```Fatal Exception: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
       at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1963)
       at java.util.HashMap$TreeNode.treeify(HashMap.java:2079)
       at java.util.HashMap.treeifyBin(HashMap.java:768)
       at java.util.HashMap.putVal(HashMap.java:640)
       at java.util.HashMap.put(HashMap.java:608)
       at com.google.maps.api.android.lib6.phoenix.cv.d(:com.google.android.gms.policy_maps_core_dynamite@240506509@240506504042.610497723.610497723:221)
       at com.google.maps.api.android.lib6.impl.eo.run(:com.google.android.gms.policy_maps_core_dynamite@240506509@240506504042.610497723.610497723:13)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)```

**Comment by wangela** [comment]
If you would like to upvote the priority of this issue, please comment below or react on the original post above with :+1: so we can see what is popular when we triage.
--------

@aritra-tech Thank you for opening this issue. 🙏
Please check out these other resources that might help you get to a resolution in the meantime:

- [Check the issue tracker](https://developers.google.com/maps/support/#issue_tracker) - bugs and feature requests for Google Maps Platform APIs and SDKs
- [Open a support case](https://developers.google.com/maps/support#contact-maps-support) - Get 1:1 support in Cloud Console.
- [Discord](https://discord.gg/fHTDmZe9En) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag


_This is an automated message, feel free to ignore._

**Comment by binayshaw7777** [comment]
@kikoso Hey, sorry for the late response. We are working together and we found out multiple instance of this from Firebase Crashlytics log. This is from the prod release crash log and never faced this ourselves, hence we can't reproduce it.

**Comment by aritra-tech** [comment]
Hey, @kikoso in our debug build it's working fine but in `prod` it's getting multiple instances. It is mainly happening on `Android 14`and after checking the logs whenever the user comes to the `Map Screen` it crashes.

Is it occurring because the version of google maps compose?

**Comment by eckoj433** [comment]
> Hey, @kikoso in our debug build it's working fine but in `prod` it's getting multiple instances. It is mainly happening on `Android 14`and after checking the logs whenever the user comes to the `Map Screen` it crashes.
> 
> Is it occurring because the version of google maps compose?

having the same exact issue, can not reproduce but seeing it in crashlytics. We however have an even spread of android 11, 12, 13 and 14.

**Comment by ChristophKaser** [comment]
I am seeing the same issue (in production) with a Mapview without compose, so it seems to be a concurrency issue in the Google Maps Library.

**Comment by thelaunchengine** [comment]
## Additional production signal (WhaleAlert Android)

Seeing the same fatal crash in production via Sentry (**ANDROID-4B**, 72 events / 9 users, Feb–Jul 2026):

`ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode`

Stack is entirely inside Play Services Maps Dynamite phoenix (no app frames), e.g.:

```
at java.util.HashMap$TreeNode.moveRootToFront
at java.util.HashMap$TreeNode.treeify
at java.util.HashMap.treeifyBin
at java.util.HashMap.putVal / put
at com.google.maps.api.android.lib6.phoenix.du.m (:policy_maps_core_dynamite@260830207@…)
at com.google.maps.api.android.lib6.phoenix.dm.d
at com.google.maps.api.android.lib6.impl.er.run
at java.util.concurrent.ThreadPoolExecutor…
```

- Client: `play-services-maps:20.0.0` (not Compose Maps)
- Device GMS Maps modules: **26.16.31** and **26.25.32**
- Stages: `map_ready` / `map_loaded`
- OS: Android 13, 15, 16

Will also file on Issue Tracker component **188870** (Maps SDK for Android) as recommended when this was closed.

**Comment by kikoso** [comment]
Hi @thelaunchengine . If this is not happening on `maps-compose`, please consider opening an issue at the [issue tracker](https://developers.google.com/maps/support/#issue_tracker), so it can be properly prioritised. Thanks!

**Comment by thelaunchengine** [comment]
**Update:** Filed on Google Issue Tracker as requested:

https://issuetracker.google.com/issues/534394045

Includes production stack (policy_maps_core_dynamite phoenix / HashMap TreeNode), GMS Maps **26.25.32**, and Sentry ANDROID-4B volume.
