### ISSUE TITLE
Using Marker or MarkerComposable in Clustering

### ISSUE THREAD

**Issue by feivur** [googlemaps/android-maps-compose#641]
**Is your feature request related to a problem? Please describe.**
Now we cannot use Marker or MarkerComposable in blocks clusterContent and clusterItemContent of Clustering (com.google.maps.android.compose.clustering.Clustering)
Therefore, it is not possible to drag and drop custom markers.

 **Describe the solution you'd like**
I want to use features together: custom markers, dragging and clustering.

MarkerComposableinside Clustering leads to a crash: case 1
java.lang.IllegalStateException: The ComposeView was measured to have a width or height of zero. Make sure that the content has a non-zero size.

Marker inside Clustering leads to a crash: case 2
java.lang.IllegalStateException: Invalid applier

maps-compose version is 6.1.2

### Case 1
```
@Composable
private fun CustomUiClustering(items: List<MyItem>) {
    Clustering(
        items = items,
        clusterItemContent = {
            MarkerComposable(
                state = rememberMarkerState(position = it.itemPosition)
            ) {
                Text(
                    modifier = Modifier.size(40.dp),
                    text = "test",
                )
            }
        }
    )
}
```

```
FATAL EXCEPTION: main
                     Process: com.google.maps.android.compose, PID: 28881
                     java.lang.IllegalStateException: The ComposeView was measured to have a width or height of zero. Make sure that the content has a non-zero size.
                     	at com.google.maps.android.compose.RememberComposeBitmapDescriptorKt.renderComposableToBitmapDescriptor(RememberComposeBitmapDescriptor.kt:58)
                     	at com.google.maps.android.compose.RememberComposeBitmapDescriptorKt.access$renderComposableToBitmapDescriptor(RememberComposeBitmapDescriptor.kt:1)
                     	at com.google.maps.android.compose.RememberComposeBitmapDescriptorKt.rememberComposeBitmapDescriptor(RememberComposeBitmapDescriptor.kt:29)
                     	at com.google.maps.android.compose.MarkerKt.MarkerComposable-Khg_OnI(Marker.kt:313)
                     	at com.google.maps.android.compose.markerexamples.ComposableSingletons$MarkerClusteringActivityKt$lambda-3$1.invoke(MarkerClusteringActivity.kt:172)
                     	at com.google.maps.android.compose.markerexamples.ComposableSingletons$MarkerClusteringActivityKt$lambda-3$1.invoke(MarkerClusteringActivity.kt:171)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer$createAndAddView$view$2.invoke(ClusterRenderer.kt:95)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer$createAndAddView$view$2.invoke(ClusterRenderer.kt:95)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer$InvalidatingComposeView.Content(ClusterRenderer.kt:220)
                     	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:259)
                     	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:258)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                     	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:216)
                     	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:132)
                     	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:131)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                     	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:121)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:155)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:154)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:154)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:133)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:97)
                     	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3595)
                     	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3522)
                     	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:743)
                     	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1122)
                     	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3876)
                     	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
                     	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                     	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1631)
                     	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:124)
                     	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:180)
                     	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
                     	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                     	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1712)
                     	at android.view.View.dispatchAttachedToWindow(View.java:23244)
                     	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3722)
                     	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3729)
                     	at android.view.ViewGroup.addViewInner(ViewGroup.java:5604)
                     	at android.view.ViewGroup.addView(ViewGroup.java:5352)
                     	at android.view.ViewGroup.addView(ViewGroup.java:5292)
                     	at android.view.ViewGroup.addView(ViewGroup.java:5264)
                     	at com.google.maps.android.compose.MapComposeViewRenderKt.startRenderingComposeView(MapComposeViewRender.kt:46)
                     	at com.google.maps.android.compose.MapComposeViewRenderKt$rememberComposeUiViewRenderer$1$1.startRenderingView(MapComposeViewRender.kt:92)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.createAndAddView(ClusterRenderer.kt:99)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.onClustersChanged(ClusterRenderer.kt:67)
                     	at com.google.maps.android.clustering.ClusterManager$ClusterTask.onPostExecute(ClusterManager.java:322)
                     	at com.google.maps.android.clustering.ClusterManager$ClusterTask.onPostExecute(ClusterManager.java:308)
                     	at android.os.AsyncTask.finish(AsyncTask.java:771)
                     	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
                     	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
                     	at android.os.Handler.dispatchMessage(Handler.java:106)
                     	at android.os.Looper.loopOnce(Looper.java:230)
                     	at android.os.Looper.loop(Looper.java:319)
                     	at android.app.ActivityThread.main(ActivityThread.java:9063)
                     	at java.lang.reflect.Method.invoke(Native Method)
                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```

### Case 2

```
@Composable
private fun CustomUiClustering(items: List<MyItem>) {
    Clustering(
        items = items,
        clusterItemContent = {
            Marker(
                state = rememberMarkerState(position = it.itemPosition)
            )
        }
    )
}
```

```
FATAL EXCEPTION: main
                     Process: com.google.maps.android.compose, PID: 32440
                     java.lang.IllegalStateException: Invalid applier
                     	at androidx.compose.runtime.ComposablesKt.invalidApplier(Composables.kt:476)
                     	at com.google.maps.android.compose.MarkerKt.MarkerImpl-khPtz74(Marker.kt:944)
                     	at com.google.maps.android.compose.MarkerKt.Marker-qld6geY(Marker.kt:238)
                     	at com.google.maps.android.compose.markerexamples.ComposableSingletons$MarkerClusteringActivityKt$lambda-2$1.invoke(MarkerClusteringActivity.kt:166)
                     	at com.google.maps.android.compose.markerexamples.ComposableSingletons$MarkerClusteringActivityKt$lambda-2$1.invoke(MarkerClusteringActivity.kt:165)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer$createAndAddView$view$2.invoke(ClusterRenderer.kt:95)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer$createAndAddView$view$2.invoke(ClusterRenderer.kt:95)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer$InvalidatingComposeView.Content(ClusterRenderer.kt:220)
                     	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:259)
                     	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:258)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                     	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:216)
                     	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:132)
                     	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:131)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                     	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:121)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:155)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:154)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:154)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:133)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                     	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                     	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:97)
                     	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3595)
                     	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3522)
                     	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:743)
                     	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1122)
                     	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3876)
                     	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
                     	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                     	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1631)
                     	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:124)
                     	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:180)
                     	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
                     	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                     	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                     	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1712)
                     	at android.view.View.dispatchAttachedToWindow(View.java:23244)
                     	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3722)
                     	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3729)
                     	at android.view.ViewGroup.addViewInner(ViewGroup.java:5604)
                     	at android.view.ViewGroup.addView(ViewGroup.java:5352)
                     	at android.view.ViewGroup.addView(ViewGroup.java:5292)
                     	at android.view.ViewGroup.addView(ViewGroup.java:5264)
                     	at com.google.maps.android.compose.MapComposeViewRenderKt.startRenderingComposeView(MapComposeViewRender.kt:46)
                     	at com.google.maps.android.compose.MapComposeViewRenderKt$rememberComposeUiViewRenderer$1$1.startRenderingView(MapComposeViewRender.kt:92)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.createAndAddView(ClusterRenderer.kt:99)
                     	at com.google.maps.android.compose.clustering.ComposeUiClusterRenderer.onClustersChanged(ClusterRenderer.kt:67)
                     	at com.google.maps.android.clustering.ClusterManager$ClusterTask.onPostExecute(ClusterManager.java:322)
                     	at com.google.maps.android.clustering.ClusterManager$ClusterTask.onPostExecute(ClusterManager.java:308)
                     	at android.os.AsyncTask.finish(AsyncTask.java:771)
                     	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
                     	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
                     	at android.os.Handler.dispatchMessage(Handler.java:106)
                     	at android.os.Looper.loopOnce(Looper.java:230)
                     	at android.os.Looper.loop(Looper.java:319)
                     	at android.app.ActivityThread.main(ActivityThread.java:9063)
                     	at java.lang.reflect.Method.invoke(Native Method)
                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by ln-12** [comment]
We are also experiencing case 1. This issue seems to be a follow up to this [issue](https://github.com/googlemaps/android-maps-compose/issues/518)/[PR](https://github.com/googlemaps/android-maps-compose/pull/533)/[comment](https://github.com/googlemaps/android-maps-compose/pull/533#discussion_r1846627388).

I our case it also happens without clustering (also on v6.1.2):
```kotlin
MyGoogleMap(
    cameraPositionState = cameraPositionState,
    uiSettings = MapUiSettings(
        compassEnabled = false,
        indoorLevelPickerEnabled = false,
        mapToolbarEnabled = false,
        myLocationButtonEnabled = false,
        rotationGesturesEnabled = false,
        scrollGesturesEnabled = false,
        scrollGesturesEnabledDuringRotateOrZoom = false,
        tiltGesturesEnabled = false,
        zoomControlsEnabled = false,
        zoomGesturesEnabled = false,
    ),
    liteMode = true,
    modifier = Modifier
        .height(115.dp)
        .fillMaxWidth(),
) {
    val markerState = remember(coordinates) { MarkerState(position = coordinates) }
    MarkerComposable(
        state = markerState,
        title = stringResource(R.string.some_description),
    ) {
        Icon(
            imageVector = MyDrawables.MapMarker,
            contentDescription = null,
            tint = Color.Blue,
            modifier = Modifier.size(16.dp),
        )
    }
}
```

I am already defining a `size` for the icon, so my only idea would be to use `requiredSize` instead to ignore any incoming constraints. Do you think that would help? Unfortunately this issue is relatively rare and we could not reproduce it yet locally, only ours users are able to get it.

**Comment by ln-12** [comment]
I have additional information. The requireSize modifier did not help with that crash. However, I copied the `rememberComposeBitmapDescriptor` implementation and added a workaround that helps + some logging [here](https://github.com/googlemaps/android-maps-compose/blob/212f3aff55624d8c3b0c8e414c88d97e145113d1/maps-compose/src/main/java/com/google/maps/android/compose/RememberComposeBitmapDescriptor.kt#L57-L60):

```kotlin
    if (composeView.measuredWidth == 0 || composeView.measuredHeight == 0) {
        val ex = IllegalStateException(
            "The ComposeView was measured to have a width or height of " +
                "zero. Make sure that the content has a non-zero size.",
        )

        Logger.ex(
            ex = ex,
            message = "Parent: size=${parent.size}, width=${parent.width}, height=${parent.height}\n" +
                "Compose view: size=${composeView.size}, width=${composeView.width}, height=${composeView.height}\n" +
                "Measured: width=${composeView.measuredWidth}, height=${composeView.measuredHeight}",
        )

        return null
    }
```

The result is the following:
```
Parent: size=2, width=1080, height=1862
Compose view: size=1, width=0, height=0
Measured: width=0, height=0
```

So apparently the actual issue not the parent having a zero width/height but rather the compose view not being measured correctly.

**Comment by mariohide** [comment]
In my case, it's not related to clustering. I have fragments in a ViewPager, and a Compose map in one of the fragments. When the fragment becomes invisible and the marker data source changes, a crash occurs.

To work around this issue, I added a boolean flag:

```kotlin
if (uiState.isContainerVisible) {
    uiState.markers.forEach { marker ->
        MarkerComposable(...) {
            CustomMarker(marker)
        }
    }
}
```
`isContainerVisible` is set to true 200ms after the fragment resumes and to false when the fragment pauses.

**Comment by bubenheimer** [comment]
@mariohide are you able to provide a complete and somewhat minimal repro? I am not a maintainer, but I think a good repro may help with seeing this fixed, as it seems to happen in specific circumstances.

Right now this issue does not seem to have a stacktrace for the non-clustering case. The non-clustering codebase is somewhat different from (simpler than) the clustering kind.

**Comment by mariohide** [comment]
Sure, I will do that after my busy days.

Uli Bubenheimer ***@***.***> 于 2024年12月30日周一 22:16写道：

**Comment by mariohide** [comment]
@bubenheimer Hi, I've create a [repo](https://github.com/mariohide/MarkerCrash) that reproduce this:

 1. Build and install;
 2. Navigate to "fragment2";
 3.  click "Add marker cause crash" button.
 
You got a crash.

**Comment by bubenheimer** [comment]
Thanks for the repro, that should be very helpful. I took a quick look: you should set Modifier.requiredSize() on the Image, otherwise it may be zero size. However, that is not enough: the crash persists.

You can use `ViewCompositionStrategy.DisposeOnDetachedFromWindow` on your Map Fragment composition to work around the issue; this will dispose the composition a lot more than before, though: I think it will essentially dispose the composition whenever the fragment is not current in the pager.

Here is the stacktrace:

```
java.lang.IllegalStateException: The ComposeView was measured to have a width or height of zero. Make sure that the content has a non-zero size.
	at com.google.maps.android.compose.RememberComposeBitmapDescriptorKt.renderComposableToBitmapDescriptor(RememberComposeBitmapDescriptor.kt:58)
	at com.google.maps.android.compose.RememberComposeBitmapDescriptorKt.access$renderComposableToBitmapDescriptor(RememberComposeBitmapDescriptor.kt:1)
	at com.google.maps.android.compose.RememberComposeBitmapDescriptorKt.rememberComposeBitmapDescriptor(RememberComposeBitmapDescriptor.kt:29)
	at com.google.maps.android.compose.MarkerKt.MarkerComposable-Khg_OnI(Marker.kt:313)
	at code.bug.map.ComposeMapFragmentKt$MapWithMarker$1.invoke(ComposeMapFragment.kt:55)
	at code.bug.map.ComposeMapFragmentKt$MapWithMarker$1.invoke(ComposeMapFragment.kt:53)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2825)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:3116)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3607)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3552)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:948)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1206)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:132)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:616)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:585)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1564)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1575)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1175)
	at android.view.Choreographer.doFrame(Choreographer.java:1100)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1549)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8875)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:891)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@4c218af, androidx.compose.ui.platform.MotionDurationScaleImpl@8404bc, StandaloneCoroutine{Cancelling}@70f7c45, AndroidUiDispatcher@bd31f9a]
```

The ComposeView is zero measured size here, presumably due to the Fragment View not currently being displayed on the screen.

A maintainer may need to address this, I'm not sure how to best fix it; I'm no expert on the Android View system.

My thinking is, if the ComposeView cannot be forced to the size we want when the parent View is zero size, then we should not use the parent. We could draw into some sort of offline View, but we'd lose all inherited "attributes" from the parent View, including View attributes and Compose attributes. It may be sufficient to install the CompositionContext from the parent View on the offline View composition to preserve Compose attributes, but not sure how to preserve View attributes, or if that is necessary.

Also, additional work may be needed for the clustering case, it uses a more sophisticated approach for certain things.

**Comment by ln-12** [comment]
@bubenheimer Thanks for looking into this topic again! 

You mention the use of the `requiredSize` modifier. As I [also found out above](https://github.com/googlemaps/android-maps-compose/issues/641#issuecomment-2493641530), this is not enough to fix the crash.
From a user/consumer perspective, I think that the min required size (of 1x1) should be handled within the `MarkerComposable` itself as it is specific to the internal implementation and easy to misuse/forget.

**Comment by Abdelsattar** [comment]
Thanks @mariohide for sharing this workaround, I have used it and it worked until we can get a propre soultion from Maps.

**Comment by CarloskHard** [comment]
I am experiencing the same issue. Is there any solve yet? I can't use clusters because of this

**Comment by kikoso** [comment]
> [@bubenheimer](https://github.com/bubenheimer) Hi, I've created a [repo](https://github.com/mariohide/MarkerCrash) that reproduce this:
> 
> 1. Build and install;
> 2. Navigate to "fragment2";
> 3. click "Add marker cause crash" button.
> 
> You got a crash.

@Mariohide, hijacking this thread to attempt an explanation at what’s going on in your example.

When you navigate to the second fragment in the ViewPager, the fragment displaying the map is no longer visible. You can easily confirm this using the Layout Inspector. Since the state is shared between both fragments, it attempts to update the now non-visible fragment (which has no size), and that’s when the problem occurs. In the latest version, this should no longer lead to a crash, though.

I’m not entirely sure this can be resolved from a Compose perspective. If a Composable is hosted in a fragment with a size of 0 or that is not visible, it will naturally report a measured size of 0 due to the way layout and drawing work. Possible mitigations include throwing an exception, setting a fallback size (e.g., 1dp), or using a placeholder view, but ultimately, the root cause is that the Composable is not on screen when it's being updated.

**Comment by brucemok8** [comment]
It seems the discussion has drifted from the original clustering issue.

The core problem is that Marker/MarkerComposable cannot be used inside clusterContent or clusterItemContent in Clustering.

In our case, this prevents us from animating marker position changes. With non-clustered markers, we can use Animatable to smoothly update markerState.position. However, with clustering, we only provide clusterItemContent and lose control over individual marker states, so smooth position updates are no longer possible.

Is this a known limitation, or is there a recommended way to support marker animations when clustering is enabled?

Should I open a new issue to discuss this?

**Comment by yohan-bittan** [comment]
Hello 👋 

Do you have any visibility on the fix availability on the library side?
It's causing thousands of crashes a day on our side and on my side We're not using a fragment/viewpager but a simple activity and it is still crashing...

**Comment by el-qq** [comment]
However, MarkerComposable works with `clusterItemDecoration`
```

        clusterItemContent = {},
        clusterItemDecoration = { item ->
            MarkerComposable(
                state = rememberUpdatedMarkerState(item.position),
                anchor = Offset(0.5f, 1.0f),
                zIndex = item.zIndex,
                title = item.title,
                snippet = item.snippet,
            ) {
                Icon(
                    imageVector = Icons.Default.LocationOn,
                    contentDescription = null,
                    tint = Color.Yellow,
                    modifier = Modifier.size(32.dp),
                )
            }
        },
```

**Comment by el-qq** [comment]
So, a working version of MarkerComposable support in Clustering.clusterItemContent has been implemented in a [separate PR](https://github.com/el-qq/android-maps-compose/pull/1)

Since this PR touches core parts of marker rendering and event handling, the proposed approach requires review and sign-off from the project maintainers
