### ISSUE TITLE
Map Snapshots

### ISSUE THREAD

**Issue by MobileAppsGO** [googlemaps/android-maps-compose#86]
Please add support for taking map snapshots:
**GoogleMap::snapshot(@NonNull GoogleMap.SnapshotReadyCallback callback)**

**Comment by jpoehnelt** [comment]
@MobileAppsGO Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)


_This is an automated message, feel free to ignore._

**Comment by recoverrelax** [comment]
I would also want this feature. Thanks!

**Comment by recoverrelax** [comment]
any updates on this?

**Comment by arriolac** [comment]
@recoverrelax you can use `MapEffect` to get the snapshot.

Something like:

```
GoogleMap {
   MapEffect { map ->
      map.snapshot { snapshot ->
         // Got snapshot here
      }
   }
}
```

**Comment by perdona** [comment]
Is this going to be an official feature? It would be very nice to have a map span to base snapshot on, cause CameraPosition is very limited to handle multiple markers with a good framing displaying all markers.

**Comment by perdona** [comment]
Yes.. I think we should have other options of zoom, since in my case I need to frame multiple markers, and set the snapshot with a zoom that will show every marker wihtout being too far.

**Comment by pranandpatil** [comment]
Any update on this?
Is snapshot functionality is available ?

**Comment by petros-chariskos** [comment]
I have been using in production the recommend by @arriolac code snippet:
```
GoogleMap {
   MapEffect { map ->
      map.snapshot { snapshot ->
         // Got snapshot here
      }
   }
}
```
and is working. The downside is that in very rare cases and completely randomly it throws:
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
    	at android.graphics.Canvas.<init>(Canvas.java:113)
    	at com.google.maps.api.android.lib6.impl.a.a(:com.google.android.gms.policy_maps_core_dynamite@233610103@233610101065.570495220.570495220:3)
    	at com.google.maps.api.android.lib6.phoenix.cb.run(:com.google.android.gms.policy_maps_core_dynamite@233610103@233610101065.570495220.570495220:9)
    	at android.os.Handler.handleCallback(Handler.java:958)
    	at android.os.Handler.dispatchMessage(Handler.java:99)
    	at android.os.Looper.loopOnce(Looper.java:205)
    	at android.os.Looper.loop(Looper.java:294)
    	at android.app.ActivityThread.main(ActivityThread.java:8194)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
maybe because `MapEffect` is still `experimental`? Will it be any update any time soon?

**Comment by easydev991** [comment]
We are still waiting for the stable official implementation, correct?

**Comment by alexandrupele** [comment]
@petros-chariskos i twas able to fix that NPE by putting that MapEffect behind a callback of "onMapLoaded". It's a parameter for GoogleMap. Try it, I hope it helps. I never seen the NPE ever since.

**Comment by petros-chariskos** [comment]
thank you @alexandrupele, I am already doing that and still getting the NPE. I can give the code snippet in case there is something wrong with my implementation but I think it's pretty straight forward.

```
var isMapLoaded by remember { mutableStateOf(false) }
val mapBitmap: MutableState<Bitmap?> = remember { mutableStateOf(null) }

GoogleMap(
    modifier = Modifier,
    cameraPositionState = cameraPositionState,
    properties = mapProperties,
    uiSettings = uiSettings,
    onMapLoaded = {
        isMapLoaded = true
    }
) {
    MapMarker(
        context = LocalContext.current,
        state = rememberMarkerState(position = LatLng(latLng.latitude, latLng.longitude)),
        iconResourceId = iconResourceId
    )

    if (isMapLoaded) {
        MapEffect { map ->
            map.snapshot { snapshot ->
                mapBitmap.value = snapshot
            }
        }
    }
}
```

**Comment by devjorgecastro** [comment]
> thank you @alexandrupele, I am already doing that and still getting the NPE. I can give the code snippet in case there is something wrong with my implementation but I think it's pretty straight forward.
> 
> ```
> var isMapLoaded by remember { mutableStateOf(false) }
> val mapBitmap: MutableState<Bitmap?> = remember { mutableStateOf(null) }
> 
> GoogleMap(
>     modifier = Modifier,
>     cameraPositionState = cameraPositionState,
>     properties = mapProperties,
>     uiSettings = uiSettings,
>     onMapLoaded = {
>         isMapLoaded = true
>     }
> ) {
>     MapMarker(
>         context = LocalContext.current,
>         state = rememberMarkerState(position = LatLng(latLng.latitude, latLng.longitude)),
>         iconResourceId = iconResourceId
>     )
> 
>     if (isMapLoaded) {
>         MapEffect { map ->
>             map.snapshot { snapshot ->
>                 mapBitmap.value = snapshot
>             }
>         }
>     }
> }
> ```

I have tested this code trying to create a snapshot of the map and it causes infinite recompositions when the line is executed:
`mapBitmap.value = snapshot`

I have tested this code trying to create a snapshot of the map and it causes infinite recompositions when the line is executed

Any idea why this problem? any solution? 😕

**Comment by JuanFranCrater** [comment]
Hi! Is this feature still being working on? Or any other way to access the googleMap instance without the use of MapEffect?Thanks!

**Comment by Badranh** [comment]
Would be awesome to have this feature +1

**Comment by alexandrupele** [comment]
@petros-chariskos try updating to compose maps 4.3.3. I see they've fixed a few things about the phase of the composition at which point the map is rendered. Let me know if it fixes it for you. I've also seen this crash again, now I'm hoping it goes away with the new version. I had 4.3.0 before.

**Comment by alexandrupele** [comment]
I still get this crash. Anyone found a solution for it?

**Comment by alexandrupele** [comment]
@petros-chariskos check this thread until the end, i think the answer is there: https://issuetracker.google.com/issues/290806747
